/*
 * kernel/crypto.c — the cryptographic primitives TLS is built on:
 * SHA-256, HMAC-SHA256, the TLS 1.2 PRF (RFC 5246 section 5), and
 * AES-128-GCM (NIST SP 800-38D) -- the record-layer AEAD cipher for
 * TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.
 *
 * Every primitive here was implemented against its specification and
 * independently verified against known-answer test vectors *before*
 * being adapted into this file — not just "it compiles." SHA-256
 * against NIST's published vectors, HMAC-SHA256 against RFC 4231, the
 * PRF cross-checked against a from-scratch Python reimplementation of
 * the same RFC 5246 construction, AES-128 against FIPS-197's own
 * worked example plus independently-generated vectors cross-checked
 * against OpenSSL, and GCM against vectors cross-checked against
 * PyCryptodome (whose empty-message/all-zero-key tag independently
 * reproduces the well-known published NIST GCM test case 1 value,
 * confirming that reference implementation itself is trustworthy) --
 * including negative tests confirming a tampered ciphertext, tag, or
 * AAD is correctly *rejected*, not just that valid data round-trips.
 *
 * Crypto bugs are a different class of risk from the rest of this
 * kernel: a wrong PE loader bound check crashes visibly, but a wrong
 * hash, PRF, or cipher can produce output that looks plausible and is
 * silently insecure. This file's own development caught exactly that
 * shape of bug twice — a hand-transcribed test string with a
 * one-character length error that produced a wrong-but-plausible-
 * looking HMAC output, not a compile error or a crash — which is
 * exactly why every vector here is either a published standard or
 * mechanically generated by a second, independent implementation,
 * never hand-copied hex. See SECURITY.md for the full verification
 * methodology and what this file deliberately does not attempt
 * (constant-time execution against timing side channels beyond the
 * GCM tag comparison — see that file for why).
 */
#include "kernel.h"

/* ---- SHA-256 (FIPS 180-4) ------------------------------------------- */

static const u32 sha256_k[64] = {
    0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
    0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
    0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
    0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
    0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
    0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2,
};

static u32 rotr32(u32 x, u32 n) { return (x >> n) | (x << (32 - n)); }

static void sha256_block(sha256_ctx_t *ctx, const u8 *block)
{
    u32 w[64];
    for (int i = 0; i < 16; i++)
        w[i] = ((u32)block[i * 4] << 24) | ((u32)block[i * 4 + 1] << 16) |
               ((u32)block[i * 4 + 2] << 8) | block[i * 4 + 3];
    for (int i = 16; i < 64; i++) {
        u32 s0 = rotr32(w[i - 15], 7) ^ rotr32(w[i - 15], 18) ^ (w[i - 15] >> 3);
        u32 s1 = rotr32(w[i - 2], 17) ^ rotr32(w[i - 2], 19) ^ (w[i - 2] >> 10);
        w[i] = w[i - 16] + s0 + w[i - 7] + s1;
    }
    u32 a = ctx->h[0], b = ctx->h[1], c = ctx->h[2], d = ctx->h[3];
    u32 e = ctx->h[4], f = ctx->h[5], g = ctx->h[6], h = ctx->h[7];
    for (int i = 0; i < 64; i++) {
        u32 s1 = rotr32(e, 6) ^ rotr32(e, 11) ^ rotr32(e, 25);
        u32 ch = (e & f) ^ ((~e) & g);
        u32 t1 = h + s1 + ch + sha256_k[i] + w[i];
        u32 s0 = rotr32(a, 2) ^ rotr32(a, 13) ^ rotr32(a, 22);
        u32 maj = (a & b) ^ (a & c) ^ (b & c);
        u32 t2 = s0 + maj;
        h = g; g = f; f = e; e = d + t1; d = c; c = b; b = a; a = t1 + t2;
    }
    ctx->h[0] += a; ctx->h[1] += b; ctx->h[2] += c; ctx->h[3] += d;
    ctx->h[4] += e; ctx->h[5] += f; ctx->h[6] += g; ctx->h[7] += h;
}

void sha256_init(sha256_ctx_t *ctx)
{
    static const u32 h0[8] = {
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    };
    memcpy(ctx->h, h0, sizeof(h0));
    ctx->buf_len = 0;
    ctx->total_len = 0;
}

void sha256_update(sha256_ctx_t *ctx, const u8 *data, u64 len)
{
    ctx->total_len += len;
    while (len > 0) {
        u32 n = 64 - ctx->buf_len;
        if (n > len)
            n = (u32)len;
        memcpy(ctx->buf + ctx->buf_len, data, n);
        ctx->buf_len += n;
        data += n;
        len -= n;
        if (ctx->buf_len == 64) {
            sha256_block(ctx, ctx->buf);
            ctx->buf_len = 0;
        }
    }
}

void sha256_final(sha256_ctx_t *ctx, u8 out[32])
{
    /* captured before the padding below runs more sha256_update()
       calls that would otherwise corrupt total_len's meaning */
    u64 bitlen = ctx->total_len * 8;
    u8 pad = 0x80;
    sha256_update(ctx, &pad, 1);
    u8 zero = 0;
    while (ctx->buf_len != 56)
        sha256_update(ctx, &zero, 1);
    u8 lenbuf[8];
    for (int i = 0; i < 8; i++)
        lenbuf[i] = (u8)(bitlen >> (56 - i * 8));
    memcpy(ctx->buf + 56, lenbuf, 8);
    sha256_block(ctx, ctx->buf);
    for (int i = 0; i < 8; i++) {
        out[i * 4]     = (u8)(ctx->h[i] >> 24);
        out[i * 4 + 1] = (u8)(ctx->h[i] >> 16);
        out[i * 4 + 2] = (u8)(ctx->h[i] >> 8);
        out[i * 4 + 3] = (u8)(ctx->h[i]);
    }
}

void sha256(const u8 *data, u32 len, u8 out[32])
{
    sha256_ctx_t ctx;
    sha256_init(&ctx);
    sha256_update(&ctx, data, len);
    sha256_final(&ctx, out);
}

/* ---- HMAC-SHA256 (RFC 2104 / FIPS 198-1) ----------------------------- */

void hmac_sha256(const u8 *key, u32 key_len, const u8 *data, u32 data_len,
                 u8 out[32])
{
    u8 k[64];
    memset(k, 0, 64);
    if (key_len > 64)
        sha256(key, key_len, k);
    else
        memcpy(k, key, key_len);

    u8 ipad[64], opad[64];
    for (int i = 0; i < 64; i++) {
        ipad[i] = k[i] ^ 0x36;
        opad[i] = k[i] ^ 0x5c;
    }

    u8 inner[32];
    sha256_ctx_t ctx;
    sha256_init(&ctx);
    sha256_update(&ctx, ipad, 64);
    sha256_update(&ctx, data, data_len);
    sha256_final(&ctx, inner);

    sha256_init(&ctx);
    sha256_update(&ctx, opad, 64);
    sha256_update(&ctx, inner, 32);
    sha256_final(&ctx, out);
}

/* HMAC over two concatenated buffers without materializing the
   concatenation -- avoids a variable-length temp buffer for the
   PRF's repeated "A(i) + seed" inputs below */
static void hmac_sha256_2(const u8 *key, u32 key_len, const u8 *d1, u32 l1,
                          const u8 *d2, u32 l2, u8 out[32])
{
    u8 k[64];
    memset(k, 0, 64);
    if (key_len > 64)
        sha256(key, key_len, k);
    else
        memcpy(k, key, key_len);

    u8 ipad[64], opad[64];
    for (int i = 0; i < 64; i++) {
        ipad[i] = k[i] ^ 0x36;
        opad[i] = k[i] ^ 0x5c;
    }

    u8 inner[32];
    sha256_ctx_t ctx;
    sha256_init(&ctx);
    sha256_update(&ctx, ipad, 64);
    sha256_update(&ctx, d1, l1);
    sha256_update(&ctx, d2, l2);
    sha256_final(&ctx, inner);

    sha256_init(&ctx);
    sha256_update(&ctx, opad, 64);
    sha256_update(&ctx, inner, 32);
    sha256_final(&ctx, out);
}

/* ---- TLS 1.2 PRF (RFC 5246 section 5, P_SHA256 only -- TLS 1.2's
   cipher suites all specify SHA-256 as the PRF hash unless a suite
   says otherwise, and this only ever targets SHA-256-based suites) */

void tls_prf(const u8 *secret, u32 secret_len, const char *label,
            const u8 *seed, u32 seed_len, u8 *out, u32 out_len)
{
    /* label+seed is P_hash's own "seed" argument; 128 bytes covers
       every TLS 1.2 use here (the longest is the Finished-message
       verify_data derivation: a short label plus a 32-byte SHA-256
       handshake-transcript hash, and master-secret derivation, whose
       seed is two 32-byte randoms) with room to spare */
    u8 lseed[128];
    u32 label_len = (u32)strlen(label);
    if (label_len + seed_len > sizeof(lseed))
        return; /* never happens for this file's fixed-size callers */
    memcpy(lseed, label, label_len);
    memcpy(lseed + label_len, seed, seed_len);
    u32 lseed_len = label_len + seed_len;

    u8 a[32];
    hmac_sha256(secret, secret_len, lseed, lseed_len, a); /* A(1) */

    u32 done = 0;
    while (done < out_len) {
        u8 block[32];
        hmac_sha256_2(secret, secret_len, a, 32, lseed, lseed_len, block);
        u32 n = out_len - done < 32 ? out_len - done : 32;
        memcpy(out + done, block, n);
        done += n;
        if (done < out_len) {
            u8 next_a[32];
            hmac_sha256(secret, secret_len, a, 32, next_a);
            memcpy(a, next_a, 32);
        }
    }
}

/* ---- AES-128 (FIPS-197) ----------------------------------------------- */

static const u8 aes_sbox[256] = {
    0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,
    0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,
    0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
    0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,
    0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,
    0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
    0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,
    0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,
    0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
    0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,
    0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,
    0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
    0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,
    0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,
    0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
    0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16,
};

static const u8 aes_rcon[11] = {
    0x00,0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80,0x1b,0x36,
};

static u8 aes_xtime(u8 a) { return (u8)((a << 1) ^ ((a & 0x80) ? 0x1b : 0)); }

static u8 aes_gmul(u8 a, u8 b)
{
    u8 p = 0;
    for (int i = 0; i < 8; i++) {
        if (b & 1)
            p ^= a;
        a = aes_xtime(a);
        b >>= 1;
    }
    return p;
}

void aes128_set_key(aes128_ctx_t *ctx, const u8 key[16])
{
    memcpy(ctx->rk, key, 16);
    u8 *rk = ctx->rk;
    for (int i = 4; i < 44; i++) {
        u8 tmp[4];
        memcpy(tmp, rk + (i - 1) * 4, 4);
        if (i % 4 == 0) {
            u8 t = tmp[0];
            tmp[0] = aes_sbox[tmp[1]] ^ aes_rcon[i / 4];
            tmp[1] = aes_sbox[tmp[2]];
            tmp[2] = aes_sbox[tmp[3]];
            tmp[3] = aes_sbox[t];
        }
        for (int j = 0; j < 4; j++)
            rk[i * 4 + j] = rk[(i - 4) * 4 + j] ^ tmp[j];
    }
}

static void aes_add_round_key(u8 s[16], const u8 rk[16])
{
    for (int i = 0; i < 16; i++)
        s[i] ^= rk[i];
}

static void aes_sub_bytes(u8 s[16])
{
    for (int i = 0; i < 16; i++)
        s[i] = aes_sbox[s[i]];
}

static void aes_shift_rows(u8 s[16])
{
    u8 t;
    t = s[1]; s[1] = s[5]; s[5] = s[9]; s[9] = s[13]; s[13] = t;
    t = s[2]; s[2] = s[10]; s[10] = t;
    t = s[6]; s[6] = s[14]; s[14] = t;
    t = s[15]; s[15] = s[11]; s[11] = s[7]; s[7] = s[3]; s[3] = t;
}

static void aes_mix_columns(u8 s[16])
{
    for (int c = 0; c < 4; c++) {
        u8 *col = s + c * 4;
        u8 a0 = col[0], a1 = col[1], a2 = col[2], a3 = col[3];
        col[0] = (u8)(aes_gmul(a0, 2) ^ aes_gmul(a1, 3) ^ a2 ^ a3);
        col[1] = (u8)(a0 ^ aes_gmul(a1, 2) ^ aes_gmul(a2, 3) ^ a3);
        col[2] = (u8)(a0 ^ a1 ^ aes_gmul(a2, 2) ^ aes_gmul(a3, 3));
        col[3] = (u8)(aes_gmul(a0, 3) ^ a1 ^ a2 ^ aes_gmul(a3, 2));
    }
}

/* state is column-major (byte i lands in column i/4, row i%4) --
   matches the key schedule above's own per-column word operations */
void aes128_encrypt_block(const aes128_ctx_t *ctx, const u8 in[16], u8 out[16])
{
    u8 s[16];
    memcpy(s, in, 16);
    aes_add_round_key(s, ctx->rk);
    for (int round = 1; round <= 9; round++) {
        aes_sub_bytes(s);
        aes_shift_rows(s);
        aes_mix_columns(s);
        aes_add_round_key(s, ctx->rk + round * 16);
    }
    aes_sub_bytes(s);
    aes_shift_rows(s);
    aes_add_round_key(s, ctx->rk + 10 * 16);
    memcpy(out, s, 16);
}

/* ---- GHASH / AES-128-GCM (NIST SP 800-38D) ----------------------------
 *
 * Only ever used here with a 12-byte (96-bit) IV -- the case TLS
 * always uses, and the case SP 800-38D gives a direct construction
 * for (J0 = IV || 0^31 || 1) rather than needing the general
 * GHASH-the-IV path for other IV lengths. */

static void gf128_mul(const u8 x[16], const u8 y[16], u8 out[16])
{
    u8 z[16] = {0};
    u8 v[16];
    memcpy(v, y, 16);
    for (int i = 0; i < 128; i++) {
        int bit = (x[i / 8] >> (7 - i % 8)) & 1;
        if (bit)
            for (int j = 0; j < 16; j++)
                z[j] ^= v[j];
        int lsb = v[15] & 1;
        for (int j = 15; j > 0; j--)
            v[j] = (u8)((v[j] >> 1) | ((v[j - 1] & 1) << 7));
        v[0] = (u8)(v[0] >> 1);
        if (lsb)
            v[0] ^= 0xe1;
    }
    memcpy(out, z, 16);
}

typedef struct {
    u8 h[16];
    u8 y[16];
} ghash_ctx_t;

static void ghash_init(ghash_ctx_t *g, const u8 h[16])
{
    memcpy(g->h, h, 16);
    memset(g->y, 0, 16);
}

static void ghash_update_block(ghash_ctx_t *g, const u8 block[16])
{
    u8 xored[16];
    for (int i = 0; i < 16; i++)
        xored[i] = g->y[i] ^ block[i];
    gf128_mul(xored, g->h, g->y);
}

static void ghash_update(ghash_ctx_t *g, const u8 *data, u32 len)
{
    while (len >= 16) {
        ghash_update_block(g, data);
        data += 16;
        len -= 16;
    }
    if (len) {
        u8 block[16] = {0};
        memcpy(block, data, len);
        ghash_update_block(g, block);
    }
}

static void put_u64_be(u8 *p, u64 v)
{
    for (int i = 0; i < 8; i++)
        p[i] = (u8)(v >> (56 - i * 8));
}

/* advances only bytes [12,16) of the 16-byte counter block, per SP
   800-38D's 32-bit incrementing function inc32() -- the fixed prefix
   (J0's IV + block-counter-starts-at-1 byte) never changes */
static void gcm_inc32(u8 counter[16])
{
    for (int i = 15; i >= 12; i--)
        if (++counter[i])
            break;
}

void aes128_gcm_encrypt(const aes128_ctx_t *ctx, const u8 iv[12],
                        const u8 *aad, u32 aad_len, const u8 *pt, u32 pt_len,
                        u8 *ct, u8 tag[16])
{
    u8 h[16] = {0};
    aes128_encrypt_block(ctx, h, h);

    u8 j0[16];
    memcpy(j0, iv, 12);
    j0[12] = 0; j0[13] = 0; j0[14] = 0; j0[15] = 1;

    u8 counter[16];
    memcpy(counter, j0, 16);
    gcm_inc32(counter); /* encryption starts at J0+1; J0 itself is
                            reserved for the tag mask below */

    u32 off = 0;
    while (off < pt_len) {
        u8 ks[16];
        aes128_encrypt_block(ctx, counter, ks);
        u32 n = pt_len - off < 16 ? pt_len - off : 16;
        for (u32 i = 0; i < n; i++)
            ct[off + i] = pt[off + i] ^ ks[i];
        off += n;
        gcm_inc32(counter);
    }

    ghash_ctx_t g;
    ghash_init(&g, h);
    ghash_update(&g, aad, aad_len);
    ghash_update(&g, ct, pt_len);
    u8 lenblock[16];
    put_u64_be(lenblock, (u64)aad_len * 8);
    put_u64_be(lenblock + 8, (u64)pt_len * 8);
    ghash_update_block(&g, lenblock);

    u8 s[16];
    aes128_encrypt_block(ctx, j0, s);
    for (int i = 0; i < 16; i++)
        tag[i] = g.y[i] ^ s[i];
}

/* Returns true iff the tag verifies -- pt is only ever the correctly
   decrypted plaintext when this returns true; callers must never look
   at pt otherwise. CTR-mode decryption only runs after the tag check
   passes (no "decrypt speculatively, check after" -- an attacker who
   can observe *how far* garbage decryption proceeded before being
   discarded gains nothing here, since it simply never starts). */
bool aes128_gcm_decrypt(const aes128_ctx_t *ctx, const u8 iv[12],
                        const u8 *aad, u32 aad_len, const u8 *ct, u32 ct_len,
                        const u8 tag[16], u8 *pt)
{
    u8 h[16] = {0};
    aes128_encrypt_block(ctx, h, h);

    u8 j0[16];
    memcpy(j0, iv, 12);
    j0[12] = 0; j0[13] = 0; j0[14] = 0; j0[15] = 1;

    ghash_ctx_t g;
    ghash_init(&g, h);
    ghash_update(&g, aad, aad_len);
    ghash_update(&g, ct, ct_len);
    u8 lenblock[16];
    put_u64_be(lenblock, (u64)aad_len * 8);
    put_u64_be(lenblock + 8, (u64)ct_len * 8);
    ghash_update_block(&g, lenblock);

    u8 s[16];
    aes128_encrypt_block(ctx, j0, s);
    u8 computed_tag[16];
    for (int i = 0; i < 16; i++)
        computed_tag[i] = g.y[i] ^ s[i];

    /* every byte compared regardless of an early mismatch, rather
       than a short-circuiting memcmp, so this doesn't leak timing
       about *where* the tag diverged */
    u8 diff = 0;
    for (int i = 0; i < 16; i++)
        diff |= (u8)(computed_tag[i] ^ tag[i]);
    if (diff != 0)
        return false;

    u8 counter[16];
    memcpy(counter, j0, 16);
    gcm_inc32(counter);
    u32 off = 0;
    while (off < ct_len) {
        u8 ks[16];
        aes128_encrypt_block(ctx, counter, ks);
        u32 n = ct_len - off < 16 ? ct_len - off : 16;
        for (u32 i = 0; i < n; i++)
            pt[off + i] = ct[off + i] ^ ks[i];
        off += n;
        gcm_inc32(counter);
    }
    return true;
}

/* ---- big-integer arithmetic (for RSA verify + P-256 ECDHE) ------------
 *
 * Fixed-width, BN_LIMBS 32-bit limbs, little-endian (limb[0] is least
 * significant) -- 4096 bits, comfortably covering both an RSA-4096
 * modulus and (using only its low 8 limbs) P-256's 256-bit field.
 * Every operation here processes the full fixed width regardless of
 * the "real" size of its operands: simpler and easier to get right
 * than a variable-length representation, and performance doesn't
 * matter here -- this runs once per TLS handshake, not in a hot loop.
 *
 * bn_modexp() is also how modular inverse is computed (via Fermat's
 * little theorem, a^(p-2) mod p, valid whenever p is prime) rather
 * than a separate extended-Euclidean implementation -- one less
 * algorithm to get right, reusing code already verified elsewhere in
 * this section.
 *
 * (BN_LIMBS and bignum_t itself are declared in kernel.h, not here,
 * since ecdhe/rsa/x509 code elsewhere needs the type too.)
 */

void bn_zero(bignum_t *r) { memset(r->limb, 0, sizeof(r->limb)); }

void bn_from_bytes_be(bignum_t *r, const u8 *data, u32 len)
{
    bn_zero(r);
    for (u32 i = 0; i < len; i++) {
        u32 byte_idx = len - 1 - i;
        u32 limb_idx = i / 4;
        u32 shift = (i % 4) * 8;
        if (limb_idx < BN_LIMBS)
            r->limb[limb_idx] |= (u32)data[byte_idx] << shift;
    }
}

void bn_to_bytes_be(const bignum_t *a, u8 *out, u32 out_len)
{
    for (u32 i = 0; i < out_len; i++) {
        u32 byte_idx = out_len - 1 - i;
        u32 limb_idx = i / 4;
        u32 shift = (i % 4) * 8;
        out[byte_idx] = limb_idx < BN_LIMBS ? (u8)(a->limb[limb_idx] >> shift) : 0;
    }
}

int bn_cmp(const bignum_t *a, const bignum_t *b)
{
    for (int i = BN_LIMBS - 1; i >= 0; i--) {
        if (a->limb[i] != b->limb[i])
            return a->limb[i] > b->limb[i] ? 1 : -1;
    }
    return 0;
}

bool bn_is_zero(const bignum_t *a)
{
    for (int i = 0; i < BN_LIMBS; i++)
        if (a->limb[i])
            return false;
    return true;
}

/* r = a + b; returns the carry out (0 or 1) */
u32 bn_add(bignum_t *r, const bignum_t *a, const bignum_t *b)
{
    u64 carry = 0;
    for (int i = 0; i < BN_LIMBS; i++) {
        u64 s = (u64)a->limb[i] + b->limb[i] + carry;
        r->limb[i] = (u32)s;
        carry = s >> 32;
    }
    return (u32)carry;
}

/* r = a - b; assumes a >= b everywhere this is called (every call
   site in this file establishes that beforehand -- see e.g.
   bn_mod_wide's own invariant comment) */
u32 bn_sub(bignum_t *r, const bignum_t *a, const bignum_t *b)
{
    u64 borrow = 0;
    for (int i = 0; i < BN_LIMBS; i++) {
        u64 ai = a->limb[i];
        u64 bi = (u64)b->limb[i] + borrow;
        if (ai >= bi) {
            r->limb[i] = (u32)(ai - bi);
            borrow = 0;
        } else {
            r->limb[i] = (u32)((ai + ((u64)1 << 32)) - bi);
            borrow = 1;
        }
    }
    return (u32)borrow;
}

/* shift left by 1 bit in place; returns the bit shifted out the top */
static u32 bn_shl1(bignum_t *a)
{
    u32 carry = 0;
    for (int i = 0; i < BN_LIMBS; i++) {
        u32 new_carry = a->limb[i] >> 31;
        a->limb[i] = (a->limb[i] << 1) | carry;
        carry = new_carry;
    }
    return carry;
}

/* full a*b into a 2*BN_LIMBS-limb little-endian result */
static void bn_mul_wide(u32 *r, const bignum_t *a, const bignum_t *b)
{
    memset(r, 0, sizeof(u32) * BN_LIMBS * 2);
    for (int i = 0; i < BN_LIMBS; i++) {
        if (a->limb[i] == 0)
            continue;
        u64 carry = 0;
        for (int j = 0; j < BN_LIMBS; j++) {
            u64 p = (u64)a->limb[i] * b->limb[j] + r[i + j] + carry;
            r[i + j] = (u32)p;
            carry = p >> 32;
        }
        int k = i + BN_LIMBS;
        while (carry) {
            u64 s = (u64)r[k] + carry;
            r[k] = (u32)s;
            carry = s >> 32;
            k++;
        }
    }
}

/* Highest set bit position + 1 (i.e. the number of significant bits);
   0 if a is zero. Every loop below is bounded by this instead of the
   fixed BN_LIMBS width -- without that, every operation costs the
   same whether the real operands are 17 bits (RSA's e=65537), 256
   bits (a P-256 scalar), or the full 4096-bit width, which measured
   over 2 *seconds per modexp call* natively during this file's own
   development (let alone under QEMU's CPU emulation, where it hung
   past a 20-second boot timeout entirely). With this bound, the same
   two realistic shapes measured under 25ms each. */
static u32 bn_bit_length(const bignum_t *a)
{
    for (int i = BN_LIMBS - 1; i >= 0; i--) {
        if (a->limb[i]) {
            u32 v = a->limb[i];
            u32 bits = 0;
            while (v) { bits++; v >>= 1; }
            return (u32)i * 32 + bits;
        }
    }
    return 0;
}

/* wide_a mod n -> r (BN_LIMBS limbs): binary long division, one bit
   of wide_a at a time, MSB to LSB, processing only the top_bits
   significant bits of wide_a (see bn_bit_length()'s comment above).
   rem stays < n before every shift (loop invariant, true initially
   since rem starts at 0 and n > 0), so after shifting left by 1 bit
   rem is < 2n -- which fits in BN_LIMBS limbs without overflow as
   long as n itself uses fewer than the full BN_LIMBS*32 bits (true
   for every modulus this file ever calls this with: RSA moduli up to
   4096 bits and P-256's 256-bit prime both leave headroom in a
   4096-bit-wide bignum_t) */
static void bn_mod_wide(bignum_t *r, const u32 *wide_a, u32 top_bits,
                        const bignum_t *n)
{
    bignum_t rem;
    bn_zero(&rem);
    for (int bit = (int)top_bits - 1; bit >= 0; bit--) {
        u32 limb_idx = (u32)bit / 32;
        u32 bitpos = (u32)bit % 32;
        u32 in_bit = (wide_a[limb_idx] >> bitpos) & 1;
        /* rem < n <= 2^(BN_LIMBS*32)-1 going into this shift (loop
           invariant), so doubling it can require one bit MORE than
           bignum_t's fixed width holds -- this only ever happens when
           n itself uses (close to) the full BN_LIMBS*32 bits, e.g. a
           genuine 4096-bit RSA modulus, which is exactly the case
           that went unexercised until this file's known-answer
           vectors included an RSA-4096 root CA and started failing.
           When that overflow bit is set, the true (unbounded) value
           is guaranteed to be >= n (n fits in BN_LIMBS*32 bits, the
           true value doesn't), so a subtraction is always required
           regardless of what the truncated bn_cmp below would say --
           and because bn_sub performs a proper mod-2^(BN_LIMBS*32)
           wraparound subtraction, "shl_carry-truncated-rem minus n"
           still comes out bit-for-bit equal to "true-value minus n"
           without needing a wider intermediate representation. */
        u32 shl_carry = bn_shl1(&rem);
        rem.limb[0] |= in_bit;
        if (shl_carry || bn_cmp(&rem, n) >= 0)
            bn_sub(&rem, &rem, n);
    }
    *r = rem;
}

void bn_mulmod(bignum_t *r, const bignum_t *a, const bignum_t *b,
              const bignum_t *n)
{
    /* a and b are always already-reduced (< n) at every call site in
       this file (bn_modexp's own loop invariant), so their product
       has at most 2*bitlen(n) significant bits -- an upper bound
       that's always safe here without computing the wide product's
       exact bit length */
    u32 wide[BN_LIMBS * 2];
    bn_mul_wide(wide, a, b);
    u32 bound = 2 * bn_bit_length(n);
    if (bound > BN_LIMBS * 2 * 32)
        bound = BN_LIMBS * 2 * 32;
    bn_mod_wide(r, wide, bound, n);
}

void bn_modexp(bignum_t *r, const bignum_t *base, const bignum_t *exp,
              const bignum_t *n)
{
    bignum_t result, b;
    bn_zero(&result);
    result.limb[0] = 1;

    /* reduce base mod n first, in case base >= n */
    u32 wide[BN_LIMBS * 2];
    memset(wide, 0, sizeof(wide));
    memcpy(wide, base->limb, sizeof(base->limb));
    bn_mod_wide(&b, wide, bn_bit_length(base), n);

    u32 exp_bits = bn_bit_length(exp); /* exp==0 -> 0 iterations -> result
                                           stays 1, i.e. x^0 == 1 */
    for (u32 i = 0; i < exp_bits; i++) {
        u32 limb_idx = i / 32, bitpos = i % 32;
        if ((exp->limb[limb_idx] >> bitpos) & 1)
            bn_mulmod(&result, &result, &b, n);
        if (i + 1 < exp_bits) /* skip the last, useless squaring -- b
                                  is never read again after this */
            bn_mulmod(&b, &b, &b, n);
    }
    *r = result;
}

/* modular inverse via Fermat's little theorem -- ONLY valid when n is
   prime (every call site in this codebase uses this exclusively for
   P-256's field prime, never for an RSA modulus, which is never
   prime) */
void bn_modinv_prime(bignum_t *r, const bignum_t *a, const bignum_t *p)
{
    bignum_t two, p_minus_2;
    bn_zero(&two);
    two.limb[0] = 2;
    bn_sub(&p_minus_2, p, &two);
    bn_modexp(r, a, &p_minus_2, p);
}

/* r = (a - b) mod p, for a,b already < p (handles the wraparound bn_sub
   alone can't: bn_sub assumes a >= b, but modular subtraction routinely
   needs a < b) */
void bn_submod(bignum_t *r, const bignum_t *a, const bignum_t *b, const bignum_t *p)
{
    if (bn_cmp(a, b) >= 0) {
        bn_sub(r, a, b);
    } else {
        bignum_t t;
        bn_add(&t, a, p);
        bn_sub(r, &t, b);
    }
}

/* r = (a + b) mod p, for a,b already < p */
void bn_addmod(bignum_t *r, const bignum_t *a, const bignum_t *b, const bignum_t *p)
{
    bignum_t t;
    u32 carry = bn_add(&t, a, b);
    if (carry || bn_cmp(&t, p) >= 0)
        bn_sub(&t, &t, p);
    *r = t;
}

/* ---- P-256 / secp256r1 (FIPS 186-4 / SEC 2) point arithmetic ----------
 *
 * Short Weierstrass curve y^2 = x^3 - 3x + b (mod p).
 *
 * Point add/double run in Jacobian coordinates (X, Y, Z), representing
 * affine (x, y) = (X/Z^2, Y/Z^3) -- NOT the textbook affine formulas,
 * which this file used at first and which turned out to be a real,
 * measured problem, not just a theoretical one: affine add/double each
 * need one modular inverse (a ~256-round Fermat modexp), and a single
 * scalar multiply calls add/double up to ~256 times each -- roughly
 * 45 *seconds* natively per scalar multiply, confirmed by timing the
 * affine version directly, and enough to hang AlphaOS's own QEMU boot
 * indefinitely once crypto_selftest() started exercising ECDHE at all
 * (the exact same shape of bug as the fixed-width bignum performance
 * bug elsewhere in this file, one level up the stack). Jacobian
 * coordinates need no inversion at all during add/double -- only at
 * the very end of a scalar multiply, converting the single final
 * result back to affine, dropping the inversion count from ~512 to 1
 * per scalar multiply.
 *
 * The Jacobian formulas below (dbl-2001-b for a=-3 doubling,
 * add-2007-bl for general addition -- both from the Explicit-Formulas
 * Database) were verified independently before being adapted here: a
 * from-scratch Python implementation of both, cross-checked against
 * the already-validated affine reference over 200 random scalars plus
 * the same 2G/3G/ECDH-consistency vectors used elsewhere in this file
 * (see scratchpad p256_jacobian_ref.py during development) -- not
 * just copied from memory and trusted, which is exactly how this
 * file's very first attempt at add-2007-bl silently dropped a factor
 * of 2 (r = S2-S1 instead of the correct r = 2*(S2-S1)) and produced
 * a wrong-but-plausible-looking point from 3G onward.
 */
typedef struct { bignum_t x, y; bool infinity; } ec_point_t;
typedef struct { bignum_t X, Y, Z; bool infinity; } ec_point_jac_t;

static bignum_t p256_p, p256_a, p256_b, p256_gx, p256_gy, p256_n;
static bool p256_ready = false;

static void p256_ensure_init(void)
{
    if (p256_ready)
        return;
    static const u8 p_b[32] = {
        0xff,0xff,0xff,0xff,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    };
    static const u8 b_b[32] = {
        0x5a,0xc6,0x35,0xd8,0xaa,0x3a,0x93,0xe7,0xb3,0xeb,0xbd,0x55,0x76,0x98,0x86,0xbc,
        0x65,0x1d,0x06,0xb0,0xcc,0x53,0xb0,0xf6,0x3b,0xce,0x3c,0x3e,0x27,0xd2,0x60,0x4b,
    };
    static const u8 gx_b[32] = {
        0x6b,0x17,0xd1,0xf2,0xe1,0x2c,0x42,0x47,0xf8,0xbc,0xe6,0xe5,0x63,0xa4,0x40,0xf2,
        0x77,0x03,0x7d,0x81,0x2d,0xeb,0x33,0xa0,0xf4,0xa1,0x39,0x45,0xd8,0x98,0xc2,0x96,
    };
    static const u8 gy_b[32] = {
        0x4f,0xe3,0x42,0xe2,0xfe,0x1a,0x7f,0x9b,0x8e,0xe7,0xeb,0x4a,0x7c,0x0f,0x9e,0x16,
        0x2b,0xce,0x33,0x57,0x6b,0x31,0x5e,0xce,0xcb,0xb6,0x40,0x68,0x37,0xbf,0x51,0xf5,
    };
    static const u8 n_b[32] = {
        0xff,0xff,0xff,0xff,0x00,0x00,0x00,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
        0xbc,0xe6,0xfa,0xad,0xa7,0x17,0x9e,0x84,0xf3,0xb9,0xca,0xc2,0xfc,0x63,0x25,0x51,
    };
    bn_from_bytes_be(&p256_p, p_b, 32);
    bn_from_bytes_be(&p256_b, b_b, 32);
    bn_from_bytes_be(&p256_gx, gx_b, 32);
    bn_from_bytes_be(&p256_gy, gy_b, 32);
    bn_from_bytes_be(&p256_n, n_b, 32);
    bn_zero(&p256_a);
    bignum_t three;
    bn_zero(&three);
    three.limb[0] = 3;
    bn_submod(&p256_a, &p256_p, &three, &p256_p); /* a = -3 mod p */
    p256_ready = true;
}

/* Jacobian doubling for a=-3 curves ("dbl-2001-b"): no modular
   inversion. */
static void jac_double(ec_point_jac_t *r, const ec_point_jac_t *p)
{
    if (p->infinity || bn_is_zero(&p->Y)) {
        r->infinity = true;
        return;
    }
    bignum_t delta, gamma, beta, x_minus_delta, x_plus_delta, three;
    bignum_t alpha, alpha2, eight_beta, x3, four_beta, four_beta_minus_x3;
    bignum_t gamma2, eight_gamma2, t1, y3, y1_plus_z1, sq, z3;
    bn_mulmod(&delta, &p->Z, &p->Z, &p256_p);
    bn_mulmod(&gamma, &p->Y, &p->Y, &p256_p);
    bn_mulmod(&beta, &p->X, &gamma, &p256_p);
    bn_submod(&x_minus_delta, &p->X, &delta, &p256_p);
    bn_addmod(&x_plus_delta, &p->X, &delta, &p256_p);
    bn_zero(&three);
    three.limb[0] = 3;
    bn_mulmod(&alpha, &x_minus_delta, &x_plus_delta, &p256_p);
    bn_mulmod(&alpha, &three, &alpha, &p256_p);

    bn_mulmod(&alpha2, &alpha, &alpha, &p256_p);
    bn_addmod(&eight_beta, &beta, &beta, &p256_p);       /* 2*beta */
    bn_addmod(&eight_beta, &eight_beta, &eight_beta, &p256_p); /* 4*beta */
    bn_addmod(&eight_beta, &eight_beta, &eight_beta, &p256_p); /* 8*beta */
    bn_submod(&x3, &alpha2, &eight_beta, &p256_p);

    bn_addmod(&four_beta, &beta, &beta, &p256_p);
    bn_addmod(&four_beta, &four_beta, &four_beta, &p256_p);
    bn_submod(&four_beta_minus_x3, &four_beta, &x3, &p256_p);
    bn_mulmod(&t1, &alpha, &four_beta_minus_x3, &p256_p);
    bn_mulmod(&gamma2, &gamma, &gamma, &p256_p);
    bn_addmod(&eight_gamma2, &gamma2, &gamma2, &p256_p);
    bn_addmod(&eight_gamma2, &eight_gamma2, &eight_gamma2, &p256_p);
    bn_addmod(&eight_gamma2, &eight_gamma2, &eight_gamma2, &p256_p);
    bn_submod(&y3, &t1, &eight_gamma2, &p256_p);

    bn_addmod(&y1_plus_z1, &p->Y, &p->Z, &p256_p);
    bn_mulmod(&sq, &y1_plus_z1, &y1_plus_z1, &p256_p);
    bn_submod(&z3, &sq, &gamma, &p256_p);
    bn_submod(&z3, &z3, &delta, &p256_p);

    r->X = x3;
    r->Y = y3;
    r->Z = z3;
    r->infinity = false;
}

/* General Jacobian+Jacobian addition ("add-2007-bl"): no modular
   inversion. Falls back to jac_double when p == q (H == 0 && r == 0
   in the formula's own notation -- unrelated to the ec_point_jac_t
   *r output parameter, just an unfortunate name collision with the
   standard formula's own "r" -- renamed rr here to avoid confusion). */
static void jac_add(ec_point_jac_t *r, const ec_point_jac_t *p, const ec_point_jac_t *q)
{
    if (p->infinity) { *r = *q; return; }
    if (q->infinity) { *r = *p; return; }

    bignum_t z1z1, z2z2, u1, u2, s1, s2, h, rr;
    bn_mulmod(&z1z1, &p->Z, &p->Z, &p256_p);
    bn_mulmod(&z2z2, &q->Z, &q->Z, &p256_p);
    bn_mulmod(&u1, &p->X, &z2z2, &p256_p);
    bn_mulmod(&u2, &q->X, &z1z1, &p256_p);
    bignum_t t1, t2;
    bn_mulmod(&t1, &p->Y, &q->Z, &p256_p);
    bn_mulmod(&s1, &t1, &z2z2, &p256_p);
    bn_mulmod(&t2, &q->Y, &p->Z, &p256_p);
    bn_mulmod(&s2, &t2, &z1z1, &p256_p);

    bn_submod(&h, &u2, &u1, &p256_p);
    bignum_t s2_minus_s1;
    bn_submod(&s2_minus_s1, &s2, &s1, &p256_p);
    if (bn_is_zero(&h)) {
        if (bn_is_zero(&s2_minus_s1)) {
            jac_double(r, p);
            return;
        }
        r->infinity = true;
        return;
    }

    bignum_t hh, i, j, v, x3, y3, z3, two_v, z1_plus_z2, sq, two_s1_j;
    bn_mulmod(&hh, &h, &h, &p256_p);
    bn_addmod(&i, &hh, &hh, &p256_p);
    bn_addmod(&i, &i, &i, &p256_p); /* i = 4*h^2 */
    bn_mulmod(&j, &h, &i, &p256_p);
    bn_addmod(&rr, &s2_minus_s1, &s2_minus_s1, &p256_p); /* rr = 2*(s2-s1) */
    bn_mulmod(&v, &u1, &i, &p256_p);

    bn_mulmod(&x3, &rr, &rr, &p256_p);
    bn_submod(&x3, &x3, &j, &p256_p);
    bn_addmod(&two_v, &v, &v, &p256_p);
    bn_submod(&x3, &x3, &two_v, &p256_p);

    bn_submod(&t1, &v, &x3, &p256_p);
    bn_mulmod(&y3, &rr, &t1, &p256_p);
    bn_mulmod(&two_s1_j, &s1, &j, &p256_p);
    bn_addmod(&two_s1_j, &two_s1_j, &two_s1_j, &p256_p);
    bn_submod(&y3, &y3, &two_s1_j, &p256_p);

    bn_addmod(&z1_plus_z2, &p->Z, &q->Z, &p256_p);
    bn_mulmod(&sq, &z1_plus_z2, &z1_plus_z2, &p256_p);
    bn_submod(&sq, &sq, &z1z1, &p256_p);
    bn_submod(&sq, &sq, &z2z2, &p256_p);
    bn_mulmod(&z3, &sq, &h, &p256_p);

    r->X = x3;
    r->Y = y3;
    r->Z = z3;
    r->infinity = false;
}

static void jac_to_affine(ec_point_t *r, const ec_point_jac_t *p)
{
    if (p->infinity) {
        r->infinity = true;
        return;
    }
    bignum_t zinv, zinv2, zinv3;
    bn_modinv_prime(&zinv, &p->Z, &p256_p); /* the ONE inversion per
                                                scalar multiply */
    bn_mulmod(&zinv2, &zinv, &zinv, &p256_p);
    bn_mulmod(&zinv3, &zinv2, &zinv, &p256_p);
    bn_mulmod(&r->x, &p->X, &zinv2, &p256_p);
    bn_mulmod(&r->y, &p->Y, &zinv3, &p256_p);
    r->infinity = false;
}

static void ec_scalar_mult(ec_point_t *r, const bignum_t *k, const ec_point_t *p)
{
    ec_point_jac_t result;
    result.infinity = true;
    ec_point_jac_t q;
    q.X = p->x;
    q.Y = p->y;
    bn_zero(&q.Z);
    q.Z.limb[0] = 1;
    q.infinity = p->infinity;
    u32 bits = bn_bit_length(k);
    for (u32 i = 0; i < bits; i++) {
        u32 li = i / 32, bp = i % 32;
        if ((k->limb[li] >> bp) & 1)
            jac_add(&result, &result, &q);
        if (i + 1 < bits)
            jac_double(&q, &q);
    }
    jac_to_affine(r, &result);
}

/* Partial public-key validation (NIST SP 800-56A section 5.6.2.3.3):
   reject the point at infinity and any (x,y) not actually satisfying
   the curve equation. P-256 has cofactor 1, so on-curve membership is
   sufficient here to rule out small-subgroup / invalid-curve attacks
   -- a peer-supplied point is never trusted for a scalar multiply
   without this check passing first. */
static bool p256_point_on_curve(const bignum_t *x, const bignum_t *y)
{
    if (bn_cmp(x, &p256_p) >= 0 || bn_cmp(y, &p256_p) >= 0)
        return false;
    bignum_t lhs, x2, x3, ax, rhs;
    bn_mulmod(&lhs, y, y, &p256_p);
    bn_mulmod(&x2, x, x, &p256_p);
    bn_mulmod(&x3, &x2, x, &p256_p);
    bn_mulmod(&ax, &p256_a, x, &p256_p);
    bn_addmod(&rhs, &x3, &ax, &p256_p);
    bn_addmod(&rhs, &rhs, &p256_b, &p256_p);
    return bn_cmp(&lhs, &rhs) == 0;
}

/* ---- x86 hardware entropy (RDRAND) -------------------------------------
 *
 * ECDHE's entire security rests on the ephemeral private scalar being
 * unpredictable -- correct point arithmetic is worthless if the key
 * that feeds it isn't. RDRAND is an on-die hardware entropy source
 * (Intel SDM vol. 1 ch. 7.3.17; supported equivalently on AMD),
 * advertised via CPUID.1:ECX bit 30. Per Intel's own guidance a single
 * RDRAND call can transiently fail (the on-chip entropy conditioner
 * underrun) and should be retried a small bounded number of times, not
 * looped forever.
 *
 * Deliberate design choice: if RDRAND isn't available, this returns
 * false and every caller (P-256 key generation) fails closed rather
 * than falling back to a weaker source (e.g. RDTSC jitter). A TLS
 * connection whose ephemeral key came from a predictable RNG is worse
 * than no TLS at all -- same reasoning as never shipping certificate
 * validation that pretends to check without actually checking. */
static bool cpu_has_rdrand(void)
{
    u32 eax, ebx, ecx, edx;
    __asm__ volatile("cpuid" : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx)
                              : "a"(1), "c"(0));
    return (ecx & (1u << 30)) != 0;
}

static bool rdrand32(u32 *out)
{
    for (int attempt = 0; attempt < 10; attempt++) {
        u8 ok;
        u32 val;
        __asm__ volatile("rdrand %0; setc %1" : "=r"(val), "=qm"(ok));
        if (ok) {
            *out = val;
            return true;
        }
    }
    return false;
}

bool crypto_random_bytes(u8 *out, u32 len)
{
    static int checked = 0;
    static bool has_rdrand = false;
    if (!checked) {
        has_rdrand = cpu_has_rdrand();
        checked = 1;
    }
    if (!has_rdrand)
        return false;
    u32 i = 0;
    while (i < len) {
        u32 v;
        if (!rdrand32(&v))
            return false;
        u32 n = len - i < 4 ? len - i : 4;
        for (u32 j = 0; j < n; j++)
            out[i + j] = (u8)(v >> (j * 8));
        i += n;
    }
    return true;
}

/* ---- P-256 ECDHE: keypair generation + shared secret ------------------- */

/* Generates a uniformly random private scalar in [1, n-1] by rejection
   sampling 32 random bytes against the group order n (rejecting the
   rare out-of-range or zero draw and redrawing -- standard technique,
   avoids the modular bias a plain "mod n" reduction would introduce),
   then computes the corresponding public point priv*G. Returns false
   if RDRAND is unavailable or fails, or in the (astronomically
   unlikely, but bounded rather than infinite-looped) case rejection
   sampling doesn't succeed within a generous attempt budget. */
bool p256_generate_keypair(u8 priv_out[32], u8 pub_x_out[32], u8 pub_y_out[32])
{
    p256_ensure_init();
    bignum_t priv;
    bool got = false;
    for (int attempt = 0; attempt < 64; attempt++) {
        u8 buf[32];
        if (!crypto_random_bytes(buf, 32))
            return false;
        bn_from_bytes_be(&priv, buf, 32);
        if (!bn_is_zero(&priv) && bn_cmp(&priv, &p256_n) < 0) {
            got = true;
            break;
        }
    }
    if (!got)
        return false;

    ec_point_t g, pub;
    g.x = p256_gx;
    g.y = p256_gy;
    g.infinity = false;
    ec_scalar_mult(&pub, &priv, &g);

    bn_to_bytes_be(&priv, priv_out, 32);
    bn_to_bytes_be(&pub.x, pub_x_out, 32);
    bn_to_bytes_be(&pub.y, pub_y_out, 32);
    return true;
}

/* Computes the ECDHE shared secret (the x-coordinate of priv*peer_pub,
   per RFC 8422 section 5.10 / TLS 1.2's ECDHE premaster secret
   definition) after validating the peer's supplied point actually
   lies on the curve. Returns false -- refusing to produce a secret at
   all -- if that validation fails, rather than silently computing a
   "shared secret" derived from an attacker-chosen invalid point. */
bool p256_ecdh_shared_secret(const u8 priv[32], const u8 peer_x[32],
                             const u8 peer_y[32], u8 shared_x_out[32])
{
    p256_ensure_init();
    ec_point_t peer;
    bn_from_bytes_be(&peer.x, peer_x, 32);
    bn_from_bytes_be(&peer.y, peer_y, 32);
    peer.infinity = false;
    if (!p256_point_on_curve(&peer.x, &peer.y))
        return false;

    bignum_t privbn;
    bn_from_bytes_be(&privbn, priv, 32);

    ec_point_t shared;
    ec_scalar_mult(&shared, &privbn, &peer);
    if (shared.infinity)
        return false; /* peer's point combined with our scalar landed on
                          infinity -- degenerate, must not be used */

    bn_to_bytes_be(&shared.x, shared_x_out, 32);
    return true;
}

static bool bytes_eq(const u8 *a, const u8 *b, u32 n)
{
    for (u32 i = 0; i < n; i++)
        if (a[i] != b[i])
            return false;
    return true;
}

/* ---- RSA signature verification (RFC 8017 RSASSA-PKCS1-v1_5-VERIFY,
   SHA-256 only) ------------------------------------------------------
 *
 * TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256's ServerKeyExchange message is
 * signed this way. Verification only ever needs the RSA *public*-key
 * operation (m = sig^e mod n, with e typically the small constant
 * 65537) -- never the private-key operation -- so bn_modexp (already
 * verified elsewhere in this file) covers the actual modular
 * exponentiation; the only thing specific to this section is checking
 * the recovered message m against the EMSA-PKCS1-v1_5 encoding:
 *   0x00 || 0x01 || PS (0xFF bytes, >= 8 of them) || 0x00 || T || H
 * where T is the fixed 19-byte DER prefix identifying "this is a
 * SHA-256 digest" (RFC 8017 section 9.2's own worked example for
 * SHA-256) and H is the 32-byte hash itself. Every byte of the
 * decoded EM is checked -- including that padding and prefix land
 * exactly where they must for the specific mod_len byte length passed
 * in, not just "does it contain the right hash somewhere" -- since a
 * loose check here is exactly the kind of bug (Bleichenbacher-style
 * low-exponent forgery via sloppy padding validation) that has broken
 * real-world PKCS#1 v1.5 verifiers before.
 */
static const u8 sha256_digestinfo_prefix[19] = {
    0x30,0x31,0x30,0x0d,0x06,0x09,0x60,0x86,0x48,0x01,0x65,0x03,0x04,0x02,0x01,0x05,0x00,0x04,0x20,
};

bool rsa_verify_pkcs1v15_sha256(const bignum_t *n, const bignum_t *e,
                                const bignum_t *sig, u32 mod_len,
                                const u8 hash[32])
{
    /* mod_len is the RSA modulus size in bytes (e.g. 256 for a
       2048-bit key); RFC 8017's own minimum is 11 bytes of framing
       (0x00 0x01 <>=8 0xFF bytes> 0x00) plus the 19-byte DigestInfo
       prefix plus the 32-byte hash, capped at this file's 4096-bit
       bignum_t width */
    if (mod_len < 11 + 19 + 32 || mod_len > 512)
        return false;
    if (bn_cmp(sig, n) >= 0)
        return false; /* signature representative must be < n (RFC 8017
                          section 8.2.2 step 1) */

    bignum_t m;
    bn_modexp(&m, sig, e, n);

    u8 em[512];
    bn_to_bytes_be(&m, em, mod_len);

    if (em[0] != 0x00 || em[1] != 0x01)
        return false;

    u32 i = 2;
    while (i < mod_len && em[i] == 0xff)
        i++;
    if (i - 2 < 8) /* RFC 8017: PS must be at least 8 bytes */
        return false;
    if (i >= mod_len || em[i] != 0x00)
        return false;
    i++;

    if (mod_len - i != sizeof(sha256_digestinfo_prefix) + 32)
        return false; /* no extra bytes before or after T||H allowed */
    if (!bytes_eq(em + i, sha256_digestinfo_prefix, sizeof(sha256_digestinfo_prefix)))
        return false;
    if (!bytes_eq(em + i + sizeof(sha256_digestinfo_prefix), hash, 32))
        return false;
    return true;
}

/* ---- self-test: known-answer vectors, checked at boot -------------------
 *
 * This isn't a "just in case" belt-and-suspenders check: crypto bugs
 * are exactly the kind that don't announce themselves the way a bad
 * PE bounds check does (a panic, a fault, an obviously wrong pixel).
 * A wrong hash or a subtly wrong PRF produces output that looks like
 * a hash or PRF output and is silently useless or worse. Every
 * primitive TLS depends on is re-verified here, at runtime, on the
 * actual compiled kernel code -- not just "the host prototype passed"
 * -- every time AlphaOS boots, before anything is ever allowed to
 * trust it for a real connection.
 */

bool crypto_selftest(void)
{
    u8 out[48];

    /* SHA-256("") */
    static const u8 sha_empty[32] = {
        0xe3,0xb0,0xc4,0x42,0x98,0xfc,0x1c,0x14,0x9a,0xfb,0xf4,0xc8,0x99,0x6f,0xb9,0x24,
        0x27,0xae,0x41,0xe4,0x64,0x9b,0x93,0x4c,0xa4,0x95,0x99,0x1b,0x78,0x52,0xb8,0x55,
    };
    sha256((const u8 *)"", 0, out);
    if (!bytes_eq(out, sha_empty, 32))
        return false;

    /* SHA-256("abc") */
    static const u8 sha_abc[32] = {
        0xba,0x78,0x16,0xbf,0x8f,0x01,0xcf,0xea,0x41,0x41,0x40,0xde,0x5d,0xae,0x22,0x23,
        0xb0,0x03,0x61,0xa3,0x96,0x17,0x7a,0x9c,0xb4,0x10,0xff,0x61,0xf2,0x00,0x15,0xad,
    };
    sha256((const u8 *)"abc", 3, out);
    if (!bytes_eq(out, sha_abc, 32))
        return false;

    /* HMAC-SHA256(key=0x0b*20, "Hi There") -- RFC 4231 test case 1 */
    static const u8 hmac_expect[32] = {
        0xb0,0x34,0x4c,0x61,0xd8,0xdb,0x38,0x53,0x5c,0xa8,0xaf,0xce,0xaf,0x0b,0xf1,0x2b,
        0x88,0x1d,0xc2,0x00,0xc9,0x83,0x3d,0xa7,0x26,0xe9,0x37,0x6c,0x2e,0x32,0xcf,0xf7,
    };
    u8 key[20];
    memset(key, 0x0b, 20);
    hmac_sha256(key, 20, (const u8 *)"Hi There", 8, out);
    if (!bytes_eq(out, hmac_expect, 32))
        return false;

    /* HMAC-SHA256(key="Jefe", "what do ya want for nothing?")
       -- RFC 4231 test case 2 */
    static const u8 hmac_expect2[32] = {
        0x5b,0xdc,0xc1,0x46,0xbf,0x60,0x75,0x4e,0x6a,0x04,0x24,0x26,0x08,0x95,0x75,0xc7,
        0x5a,0x00,0x3f,0x08,0x9d,0x27,0x39,0x83,0x9d,0xec,0x58,0xb9,0x64,0xec,0x38,0x43,
    };
    hmac_sha256((const u8 *)"Jefe", 4, (const u8 *)"what do ya want for nothing?",
               28, out);
    if (!bytes_eq(out, hmac_expect2, 32))
        return false;

    /* TLS 1.2 PRF, cross-checked against an independent from-scratch
       Python implementation of RFC 5246 section 5 (not a published
       IETF/NIST vector, since P_SHA256 alone has no widely-cited
       standalone KAT -- see kernel/crypto.c's header comment) */
    static const u8 prf_expect[48] = {
        0x41,0x41,0x4f,0x93,0x5d,0x2b,0xb6,0x9b,0x81,0x46,0x36,0xa4,0x48,0xde,0x66,0x1f,
        0x9f,0xb8,0x69,0xcb,0x36,0x4c,0xa0,0xed,0x03,0x10,0xac,0xc2,0x5c,0xbe,0x00,0x6e,
        0x45,0xdd,0xa1,0x8e,0xa4,0x69,0x7c,0x0c,0x9f,0x34,0xa3,0xa3,0x10,0x0c,0x14,0x3b,
    };
    u8 seed[64];
    for (int i = 0; i < 32; i++)
        seed[i] = (u8)i;
    for (int i = 0; i < 32; i++)
        seed[32 + i] = (u8)(32 + i);
    tls_prf((const u8 *)"test secret 0123456789abcdef", 29, "master secret",
           seed, 64, out, 48);
    if (!bytes_eq(out, prf_expect, 48))
        return false;

    /* AES-128, FIPS-197 Appendix B's own worked example */
    static const u8 aes_key[16] = {
        0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,
    };
    static const u8 aes_pt[16] = {
        0x00,0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x99,0xaa,0xbb,0xcc,0xdd,0xee,0xff,
    };
    static const u8 aes_ct[16] = {
        0x69,0xc4,0xe0,0xd8,0x6a,0x7b,0x04,0x30,0xd8,0xcd,0xb7,0x80,0x70,0xb4,0xc5,0x5a,
    };
    aes128_ctx_t actx;
    aes128_set_key(&actx, aes_key);
    aes128_encrypt_block(&actx, aes_pt, out);
    if (!bytes_eq(out, aes_ct, 16))
        return false;

    /* AES-128-GCM, the trivial all-zero case -- this specific tag is
       the well-known published NIST GCM "Test Case 1" value, not just
       something this codebase generated for itself */
    static const u8 gcm_zero_key[16] = {0};
    static const u8 gcm_zero_iv[12] = {0};
    static const u8 gcm_tag1_expect[16] = {
        0x58,0xe2,0xfc,0xce,0xfa,0x7e,0x30,0x61,0x36,0x7f,0x1d,0x57,0xa4,0xe7,0x45,0x5a,
    };
    u8 gcm_tag[16];
    aes128_set_key(&actx, gcm_zero_key);
    aes128_gcm_encrypt(&actx, gcm_zero_iv, NULL, 0, NULL, 0, NULL, gcm_tag);
    if (!bytes_eq(gcm_tag, gcm_tag1_expect, 16))
        return false;

    /* AES-128-GCM round trip + the negative cases that actually matter
       for TLS record-layer safety: a tampered ciphertext, tag, or AAD
       must all be rejected before any plaintext is trusted -- these
       don't need an external published vector, since "decrypt(encrypt(x))
       == x, and every single-bit corruption is caught" is a
       self-contained property checked against this file's own
       encrypt function, not a second implementation. */
    static const u8 gcm_key[16] = {
        0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,
    };
    static const u8 gcm_iv[12] = {
        0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1a,0x1b,
    };
    static const u8 gcm_aad[8] = {0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7};
    static const u8 gcm_pt[20] = {
        0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,
        0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x10,0x11,0x12,0x13,
    };
    u8 gcm_ct[20], gcm_tag2[16], gcm_pt_out[20];
    aes128_set_key(&actx, gcm_key);
    aes128_gcm_encrypt(&actx, gcm_iv, gcm_aad, sizeof(gcm_aad), gcm_pt,
                       sizeof(gcm_pt), gcm_ct, gcm_tag2);
    if (!aes128_gcm_decrypt(&actx, gcm_iv, gcm_aad, sizeof(gcm_aad), gcm_ct,
                            sizeof(gcm_ct), gcm_tag2, gcm_pt_out))
        return false; /* a valid tag must verify */
    if (!bytes_eq(gcm_pt_out, gcm_pt, sizeof(gcm_pt)))
        return false; /* and decrypt back to the original plaintext */

    u8 bad_ct[20];
    memcpy(bad_ct, gcm_ct, sizeof(gcm_ct));
    bad_ct[0] ^= 0x01;
    if (aes128_gcm_decrypt(&actx, gcm_iv, gcm_aad, sizeof(gcm_aad), bad_ct,
                           sizeof(bad_ct), gcm_tag2, gcm_pt_out))
        return false; /* a corrupted ciphertext must NOT verify */

    u8 bad_tag[16];
    memcpy(bad_tag, gcm_tag2, 16);
    bad_tag[0] ^= 0x01;
    if (aes128_gcm_decrypt(&actx, gcm_iv, gcm_aad, sizeof(gcm_aad), gcm_ct,
                           sizeof(gcm_ct), bad_tag, gcm_pt_out))
        return false; /* a corrupted tag must NOT verify */

    u8 bad_aad[8];
    memcpy(bad_aad, gcm_aad, sizeof(gcm_aad));
    bad_aad[0] ^= 0x01;
    if (aes128_gcm_decrypt(&actx, gcm_iv, bad_aad, sizeof(bad_aad), gcm_ct,
                           sizeof(gcm_ct), gcm_tag2, gcm_pt_out))
        return false; /* corrupted AAD must NOT verify either */

    /* bignum: mulmod + modexp, cross-checked against Python's
       arbitrary-precision pow(base, exp, mod) as an independent
       implementation of the same modular exponentiation */
    u8 bn_base_b[32], bn_exp_b[32], bn_mod_b[32], bn_out[32];
    for (int i = 0; i < 32; i++) {
        bn_base_b[i] = (u8)(i + 1);
        bn_exp_b[i] = (u8)(200 + i);
        bn_mod_b[i] = (u8)(50 + i * 3);
    }
    bn_mod_b[0] |= 0x80;
    static const u8 modexp_expect[32] = {
        0x99,0x34,0xff,0x60,0xca,0x5b,0x65,0x48,0xed,0x05,0xad,0xac,0xf1,0xfe,0x4e,0xb9,
        0x14,0x8c,0x64,0x6d,0x89,0xe8,0x59,0x88,0xc9,0x51,0xa5,0xf9,0xf3,0xbe,0xec,0x1e,
    };
    bignum_t bb, be, bm, br;
    bn_from_bytes_be(&bb, bn_base_b, 32);
    bn_from_bytes_be(&be, bn_exp_b, 32);
    bn_from_bytes_be(&bm, bn_mod_b, 32);
    bn_modexp(&br, &bb, &be, &bm);
    bn_to_bytes_be(&br, bn_out, 32);
    if (!bytes_eq(bn_out, modexp_expect, 32))
        return false;

    /* bignum: mulmod with a genuinely *full-width* (4096-bit, top bit
       set) modulus -- this exact shape (an RSA-4096 key) silently
       produced wrong results until this vector caught it: bn_mod_wide's
       inner doubling step can require one bit more than a fixed-width
       bignum_t holds whenever the modulus itself uses close to the
       full BN_LIMBS*32 bits, and the overflow bit was being silently
       discarded. Every other vector in this file uses a modulus well
       under the full width (RSA-2048, P-256's 256-bit prime), so none
       of them exercised this boundary -- cross-checked against
       Python's arbitrary-precision (base*base) % mod. */
    static const u8 mm4096_base[512] = {
        0x0b,0x12,0x19,0x20,0x27,0x2e,0x35,0x3c,0x43,0x4a,0x51,0x58,0x5f,0x66,0x6d,0x74,
        0x7b,0x82,0x89,0x90,0x97,0x9e,0xa5,0xac,0xb3,0xba,0xc1,0xc8,0xcf,0xd6,0xdd,0xe4,
        0xeb,0xf2,0xf9,0x00,0x07,0x0e,0x15,0x1c,0x23,0x2a,0x31,0x38,0x3f,0x46,0x4d,0x54,
        0x5b,0x62,0x69,0x70,0x77,0x7e,0x85,0x8c,0x93,0x9a,0xa1,0xa8,0xaf,0xb6,0xbd,0xc4,
        0xcb,0xd2,0xd9,0xe0,0xe7,0xee,0xf5,0xfc,0x03,0x0a,0x11,0x18,0x1f,0x26,0x2d,0x34,
        0x3b,0x42,0x49,0x50,0x57,0x5e,0x65,0x6c,0x73,0x7a,0x81,0x88,0x8f,0x96,0x9d,0xa4,
        0xab,0xb2,0xb9,0xc0,0xc7,0xce,0xd5,0xdc,0xe3,0xea,0xf1,0xf8,0xff,0x06,0x0d,0x14,
        0x1b,0x22,0x29,0x30,0x37,0x3e,0x45,0x4c,0x53,0x5a,0x61,0x68,0x6f,0x76,0x7d,0x84,
        0x8b,0x92,0x99,0xa0,0xa7,0xae,0xb5,0xbc,0xc3,0xca,0xd1,0xd8,0xdf,0xe6,0xed,0xf4,
        0xfb,0x02,0x09,0x10,0x17,0x1e,0x25,0x2c,0x33,0x3a,0x41,0x48,0x4f,0x56,0x5d,0x64,
        0x6b,0x72,0x79,0x80,0x87,0x8e,0x95,0x9c,0xa3,0xaa,0xb1,0xb8,0xbf,0xc6,0xcd,0xd4,
        0xdb,0xe2,0xe9,0xf0,0xf7,0xfe,0x05,0x0c,0x13,0x1a,0x21,0x28,0x2f,0x36,0x3d,0x44,
        0x4b,0x52,0x59,0x60,0x67,0x6e,0x75,0x7c,0x83,0x8a,0x91,0x98,0x9f,0xa6,0xad,0xb4,
        0xbb,0xc2,0xc9,0xd0,0xd7,0xde,0xe5,0xec,0xf3,0xfa,0x01,0x08,0x0f,0x16,0x1d,0x24,
        0x2b,0x32,0x39,0x40,0x47,0x4e,0x55,0x5c,0x63,0x6a,0x71,0x78,0x7f,0x86,0x8d,0x94,
        0x9b,0xa2,0xa9,0xb0,0xb7,0xbe,0xc5,0xcc,0xd3,0xda,0xe1,0xe8,0xef,0xf6,0xfd,0x04,
        0x0b,0x12,0x19,0x20,0x27,0x2e,0x35,0x3c,0x43,0x4a,0x51,0x58,0x5f,0x66,0x6d,0x74,
        0x7b,0x82,0x89,0x90,0x97,0x9e,0xa5,0xac,0xb3,0xba,0xc1,0xc8,0xcf,0xd6,0xdd,0xe4,
        0xeb,0xf2,0xf9,0x00,0x07,0x0e,0x15,0x1c,0x23,0x2a,0x31,0x38,0x3f,0x46,0x4d,0x54,
        0x5b,0x62,0x69,0x70,0x77,0x7e,0x85,0x8c,0x93,0x9a,0xa1,0xa8,0xaf,0xb6,0xbd,0xc4,
        0xcb,0xd2,0xd9,0xe0,0xe7,0xee,0xf5,0xfc,0x03,0x0a,0x11,0x18,0x1f,0x26,0x2d,0x34,
        0x3b,0x42,0x49,0x50,0x57,0x5e,0x65,0x6c,0x73,0x7a,0x81,0x88,0x8f,0x96,0x9d,0xa4,
        0xab,0xb2,0xb9,0xc0,0xc7,0xce,0xd5,0xdc,0xe3,0xea,0xf1,0xf8,0xff,0x06,0x0d,0x14,
        0x1b,0x22,0x29,0x30,0x37,0x3e,0x45,0x4c,0x53,0x5a,0x61,0x68,0x6f,0x76,0x7d,0x84,
        0x8b,0x92,0x99,0xa0,0xa7,0xae,0xb5,0xbc,0xc3,0xca,0xd1,0xd8,0xdf,0xe6,0xed,0xf4,
        0xfb,0x02,0x09,0x10,0x17,0x1e,0x25,0x2c,0x33,0x3a,0x41,0x48,0x4f,0x56,0x5d,0x64,
        0x6b,0x72,0x79,0x80,0x87,0x8e,0x95,0x9c,0xa3,0xaa,0xb1,0xb8,0xbf,0xc6,0xcd,0xd4,
        0xdb,0xe2,0xe9,0xf0,0xf7,0xfe,0x05,0x0c,0x13,0x1a,0x21,0x28,0x2f,0x36,0x3d,0x44,
        0x4b,0x52,0x59,0x60,0x67,0x6e,0x75,0x7c,0x83,0x8a,0x91,0x98,0x9f,0xa6,0xad,0xb4,
        0xbb,0xc2,0xc9,0xd0,0xd7,0xde,0xe5,0xec,0xf3,0xfa,0x01,0x08,0x0f,0x16,0x1d,0x24,
        0x2b,0x32,0x39,0x40,0x47,0x4e,0x55,0x5c,0x63,0x6a,0x71,0x78,0x7f,0x86,0x8d,0x94,
        0x9b,0xa2,0xa9,0xb0,0xb7,0xbe,0xc5,0xcc,0xd3,0xda,0xe1,0xe8,0xef,0xf6,0xfd,0x04,
    };
    static const u8 mm4096_mod[512] = {
        0xff,0x03,0x10,0x1d,0x2a,0x37,0x44,0x51,0x5e,0x6b,0x78,0x85,0x92,0x9f,0xac,0xb9,
        0xc6,0xd3,0xe0,0xed,0xfa,0x07,0x14,0x21,0x2e,0x3b,0x48,0x55,0x62,0x6f,0x7c,0x89,
        0x96,0xa3,0xb0,0xbd,0xca,0xd7,0xe4,0xf1,0xfe,0x0b,0x18,0x25,0x32,0x3f,0x4c,0x59,
        0x66,0x73,0x80,0x8d,0x9a,0xa7,0xb4,0xc1,0xce,0xdb,0xe8,0xf5,0x02,0x0f,0x1c,0x29,
        0x36,0x43,0x50,0x5d,0x6a,0x77,0x84,0x91,0x9e,0xab,0xb8,0xc5,0xd2,0xdf,0xec,0xf9,
        0x06,0x13,0x20,0x2d,0x3a,0x47,0x54,0x61,0x6e,0x7b,0x88,0x95,0xa2,0xaf,0xbc,0xc9,
        0xd6,0xe3,0xf0,0xfd,0x0a,0x17,0x24,0x31,0x3e,0x4b,0x58,0x65,0x72,0x7f,0x8c,0x99,
        0xa6,0xb3,0xc0,0xcd,0xda,0xe7,0xf4,0x01,0x0e,0x1b,0x28,0x35,0x42,0x4f,0x5c,0x69,
        0x76,0x83,0x90,0x9d,0xaa,0xb7,0xc4,0xd1,0xde,0xeb,0xf8,0x05,0x12,0x1f,0x2c,0x39,
        0x46,0x53,0x60,0x6d,0x7a,0x87,0x94,0xa1,0xae,0xbb,0xc8,0xd5,0xe2,0xef,0xfc,0x09,
        0x16,0x23,0x30,0x3d,0x4a,0x57,0x64,0x71,0x7e,0x8b,0x98,0xa5,0xb2,0xbf,0xcc,0xd9,
        0xe6,0xf3,0x00,0x0d,0x1a,0x27,0x34,0x41,0x4e,0x5b,0x68,0x75,0x82,0x8f,0x9c,0xa9,
        0xb6,0xc3,0xd0,0xdd,0xea,0xf7,0x04,0x11,0x1e,0x2b,0x38,0x45,0x52,0x5f,0x6c,0x79,
        0x86,0x93,0xa0,0xad,0xba,0xc7,0xd4,0xe1,0xee,0xfb,0x08,0x15,0x22,0x2f,0x3c,0x49,
        0x56,0x63,0x70,0x7d,0x8a,0x97,0xa4,0xb1,0xbe,0xcb,0xd8,0xe5,0xf2,0xff,0x0c,0x19,
        0x26,0x33,0x40,0x4d,0x5a,0x67,0x74,0x81,0x8e,0x9b,0xa8,0xb5,0xc2,0xcf,0xdc,0xe9,
        0xf6,0x03,0x10,0x1d,0x2a,0x37,0x44,0x51,0x5e,0x6b,0x78,0x85,0x92,0x9f,0xac,0xb9,
        0xc6,0xd3,0xe0,0xed,0xfa,0x07,0x14,0x21,0x2e,0x3b,0x48,0x55,0x62,0x6f,0x7c,0x89,
        0x96,0xa3,0xb0,0xbd,0xca,0xd7,0xe4,0xf1,0xfe,0x0b,0x18,0x25,0x32,0x3f,0x4c,0x59,
        0x66,0x73,0x80,0x8d,0x9a,0xa7,0xb4,0xc1,0xce,0xdb,0xe8,0xf5,0x02,0x0f,0x1c,0x29,
        0x36,0x43,0x50,0x5d,0x6a,0x77,0x84,0x91,0x9e,0xab,0xb8,0xc5,0xd2,0xdf,0xec,0xf9,
        0x06,0x13,0x20,0x2d,0x3a,0x47,0x54,0x61,0x6e,0x7b,0x88,0x95,0xa2,0xaf,0xbc,0xc9,
        0xd6,0xe3,0xf0,0xfd,0x0a,0x17,0x24,0x31,0x3e,0x4b,0x58,0x65,0x72,0x7f,0x8c,0x99,
        0xa6,0xb3,0xc0,0xcd,0xda,0xe7,0xf4,0x01,0x0e,0x1b,0x28,0x35,0x42,0x4f,0x5c,0x69,
        0x76,0x83,0x90,0x9d,0xaa,0xb7,0xc4,0xd1,0xde,0xeb,0xf8,0x05,0x12,0x1f,0x2c,0x39,
        0x46,0x53,0x60,0x6d,0x7a,0x87,0x94,0xa1,0xae,0xbb,0xc8,0xd5,0xe2,0xef,0xfc,0x09,
        0x16,0x23,0x30,0x3d,0x4a,0x57,0x64,0x71,0x7e,0x8b,0x98,0xa5,0xb2,0xbf,0xcc,0xd9,
        0xe6,0xf3,0x00,0x0d,0x1a,0x27,0x34,0x41,0x4e,0x5b,0x68,0x75,0x82,0x8f,0x9c,0xa9,
        0xb6,0xc3,0xd0,0xdd,0xea,0xf7,0x04,0x11,0x1e,0x2b,0x38,0x45,0x52,0x5f,0x6c,0x79,
        0x86,0x93,0xa0,0xad,0xba,0xc7,0xd4,0xe1,0xee,0xfb,0x08,0x15,0x22,0x2f,0x3c,0x49,
        0x56,0x63,0x70,0x7d,0x8a,0x97,0xa4,0xb1,0xbe,0xcb,0xd8,0xe5,0xf2,0xff,0x0c,0x19,
        0x26,0x33,0x40,0x4d,0x5a,0x67,0x74,0x81,0x8e,0x9b,0xa8,0xb5,0xc2,0xcf,0xdc,0xe9,
    };
    static const u8 mm4096_expect[512] = {
        0x2d,0xc5,0x9f,0xb8,0x36,0x6b,0x62,0xae,0xbd,0x3a,0x00,0xba,0xba,0xbc,0x54,0xd4,
        0x27,0xe1,0xb8,0x23,0x02,0x10,0xf2,0xb5,0xe4,0x5e,0xc0,0x81,0x26,0x42,0x3b,0x00,
        0x83,0x85,0x42,0x92,0x6f,0x18,0xbc,0x5f,0x84,0x9f,0x1b,0x3a,0x19,0xc4,0x5a,0xe4,
        0x28,0xc6,0xb4,0x74,0xa5,0x40,0x8f,0x8c,0x1c,0x6f,0xfa,0x26,0x95,0xea,0x2e,0x51,
        0x1c,0x79,0xad,0xc7,0x09,0xbe,0x49,0xee,0x1e,0x49,0x3a,0xc1,0x2c,0x86,0x11,0x20,
        0x2c,0x94,0xb5,0x84,0x4b,0x46,0x91,0x8c,0x73,0x5b,0x4c,0xa9,0xea,0x2d,0xbb,0x28,
        0x36,0xd6,0xd9,0x55,0xe1,0xb4,0x26,0x61,0x16,0x8f,0x10,0xbc,0x3d,0x8b,0xb2,0xb6,
        0xe0,0x8c,0x94,0xdf,0x78,0x78,0xdd,0x5c,0x5e,0xf6,0xb0,0xc3,0xe6,0x99,0x99,0x5f,
        0x0b,0xb1,0x1b,0x3a,0x0f,0x55,0xd8,0xf5,0x5c,0xef,0x2d,0xd2,0x06,0x9c,0xcf,0xf7,
        0x74,0x9f,0xb4,0x82,0x98,0x48,0xf7,0xb3,0x5e,0x4a,0x3c,0x57,0x3c,0x17,0x43,0xf8,
        0x4e,0xc4,0x19,0x91,0x4c,0x9b,0xec,0x4e,0x4c,0x9f,0x14,0x81,0x86,0xb4,0xb4,0xe1,
        0x6e,0x22,0xb9,0x10,0x48,0xc9,0x98,0x47,0x8a,0xf0,0x42,0x15,0x5b,0xf1,0x14,0xb2,
        0xa9,0xad,0x1a,0x4a,0x5f,0x64,0x33,0xc9,0xcb,0x79,0xaf,0xe2,0xff,0x12,0xc9,0x24,
        0xc9,0xaf,0x3e,0x15,0xda,0xa6,0xba,0x36,0xa2,0x74,0xb4,0x4a,0x06,0x26,0x64,0x6c,
        0x68,0x4c,0x6a,0x3e,0x4a,0x24,0xcc,0x4c,0x60,0x46,0xca,0xbc,0xa7,0x30,0x63,0xed,
        0x93,0xdb,0xb5,0x8a,0xe2,0x1e,0xdc,0xae,0x15,0x35,0xe2,0x0e,0x8a,0x8d,0x55,0x98,
        0x7f,0x02,0x3d,0x19,0xf8,0x50,0xb5,0xea,0xb2,0x6f,0x33,0x62,0x85,0xc2,0x88,0x7b,
        0xba,0x48,0xba,0x83,0x53,0x0a,0x37,0x08,0x6b,0x8d,0xb5,0x5e,0x30,0xf3,0xca,0xf6,
        0x61,0x8b,0xa8,0x8b,0x7f,0x0b,0xbf,0xd8,0x8a,0x49,0xf5,0xe6,0x7c,0x95,0x67,0xbb,
        0xe5,0xc8,0x8e,0x72,0x80,0x1f,0x11,0x0d,0xce,0x5b,0x54,0xc3,0x00,0x04,0x54,0x12,
        0xe8,0xdb,0x30,0x8e,0x92,0x48,0x76,0xb1,0xc0,0xa5,0xe8,0x69,0x1d,0x1f,0xd9,0xa3,
        0x37,0xae,0xf6,0xac,0x2d,0x3b,0xdf,0x43,0xee,0x19,0xb6,0x98,0xc2,0xd1,0x73,0xfb,
        0x83,0xcf,0x33,0xb6,0xe2,0x7c,0xd3,0xba,0xe4,0x91,0x75,0x09,0x3e,0xff,0xd7,0x4f,
        0x31,0x76,0x09,0x3b,0x8c,0xc8,0x96,0xfd,0xb3,0x2e,0x16,0x5c,0x43,0x6e,0x0d,0x9b,
        0x8f,0xea,0xdd,0xd0,0xf6,0x91,0x6a,0x0d,0x3d,0x73,0x74,0x87,0x1f,0x1f,0xb1,0x03,
        0x82,0xed,0x92,0xa9,0x65,0xc3,0xf7,0xca,0x2e,0x9c,0x94,0x18,0x45,0xb8,0x29,0x18,
        0x93,0x17,0x47,0x10,0x65,0x88,0x91,0x22,0x43,0x11,0xb5,0x39,0x47,0x88,0xe2,0x40,
        0xf8,0x18,0x39,0x3f,0xd3,0x7d,0x92,0xa7,0x50,0x15,0x3e,0xf6,0x91,0xe2,0x9b,0xb3,
        0x55,0x32,0x2c,0x96,0x8b,0xcd,0x84,0x1d,0x75,0x29,0x15,0x09,0x09,0x5c,0x48,0xe3,
        0xab,0xce,0x52,0xaa,0x55,0xa9,0x86,0x73,0x40,0xd3,0x24,0x5e,0x45,0xf1,0xcf,0x7c,
        0xf3,0x98,0x7e,0x88,0xd8,0xb2,0x87,0x85,0xf5,0x7a,0x7a,0xfd,0x1a,0xc6,0x9e,0xf5,
        0x24,0xdd,0x14,0xa1,0xba,0xa3,0x5f,0x9f,0x38,0x12,0xf7,0xc4,0xce,0xa5,0x9a,0xfb,
    };
    bignum_t mm_base, mm_mod, mm_result;
    bn_from_bytes_be(&mm_base, mm4096_base, 512);
    bn_from_bytes_be(&mm_mod, mm4096_mod, 512);
    bn_mulmod(&mm_result, &mm_base, &mm_base, &mm_mod);
    u8 mm_out[512];
    bn_to_bytes_be(&mm_result, mm_out, 512);
    if (!bytes_eq(mm_out, mm4096_expect, 512))
        return false;

    /* bignum: modular inverse via Fermat, against P-256's real field
       prime -- a * modinv(a, p) mod p must be exactly 1 */
    static const u8 p256_prime_b[32] = {
        0xff,0xff,0xff,0xff,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    };
    bignum_t p256, av, avinv, one_check;
    bn_from_bytes_be(&p256, p256_prime_b, 32);
    bn_zero(&av);
    av.limb[0] = 12345;
    bn_modinv_prime(&avinv, &av, &p256);
    bn_mulmod(&one_check, &av, &avinv, &p256);
    bignum_t bn_one;
    bn_zero(&bn_one);
    bn_one.limb[0] = 1;
    if (bn_cmp(&one_check, &bn_one) != 0)
        return false;

    /* bignum: add + byte round-trip */
    bignum_t bx, by, bsum;
    bn_zero(&bx);
    bx.limb[0] = 0xFFFFFFFF;
    bx.limb[1] = 0x1;
    bn_zero(&by);
    by.limb[0] = 0x1;
    u32 bn_carry = bn_add(&bsum, &bx, &by);
    if (bn_carry != 0 || bsum.limb[0] != 0 || bsum.limb[1] != 2)
        return false;

    u8 rt_in[32], rt_out[32];
    for (int i = 0; i < 32; i++)
        rt_in[i] = (u8)(i * 7 + 1);
    bignum_t rt;
    bn_from_bytes_be(&rt, rt_in, 32);
    bn_to_bytes_be(&rt, rt_out, 32);
    if (!bytes_eq(rt_out, rt_in, 32))
        return false;
    if (bn_is_zero(&rt))
        return false;
    bignum_t bn_zero_check;
    bn_zero(&bn_zero_check);
    if (!bn_is_zero(&bn_zero_check))
        return false;

    /* P-256 point arithmetic: 2G and 3G, cross-checked against an
       independent from-scratch Python reference (point_add/scalar_mult
       over the same curve equation, not this file's own code) */
    p256_ensure_init();
    ec_point_t g, two_g, three_g;
    g.x = p256_gx;
    g.y = p256_gy;
    g.infinity = false;
    ec_point_jac_t g_jac, two_g_jac, three_g_jac;
    g_jac.X = g.x;
    g_jac.Y = g.y;
    bn_zero(&g_jac.Z);
    g_jac.Z.limb[0] = 1;
    g_jac.infinity = false;
    jac_double(&two_g_jac, &g_jac);
    jac_to_affine(&two_g, &two_g_jac);
    static const u8 two_g_x[32] = {
        0x7c,0xf2,0x7b,0x18,0x8d,0x03,0x4f,0x7e,0x8a,0x52,0x38,0x03,0x04,0xb5,0x1a,0xc3,
        0xc0,0x89,0x69,0xe2,0x77,0xf2,0x1b,0x35,0xa6,0x0b,0x48,0xfc,0x47,0x66,0x99,0x78,
    };
    static const u8 two_g_y[32] = {
        0x07,0x77,0x55,0x10,0xdb,0x8e,0xd0,0x40,0x29,0x3d,0x9a,0xc6,0x9f,0x74,0x30,0xdb,
        0xba,0x7d,0xad,0xe6,0x3c,0xe9,0x82,0x29,0x9e,0x04,0xb7,0x9d,0x22,0x78,0x73,0xd1,
    };
    bn_to_bytes_be(&two_g.x, out, 32);
    if (!bytes_eq(out, two_g_x, 32))
        return false;
    bn_to_bytes_be(&two_g.y, out, 32);
    if (!bytes_eq(out, two_g_y, 32))
        return false;

    jac_add(&three_g_jac, &two_g_jac, &g_jac);
    jac_to_affine(&three_g, &three_g_jac);
    static const u8 three_g_x[32] = {
        0x5e,0xcb,0xe4,0xd1,0xa6,0x33,0x0a,0x44,0xc8,0xf7,0xef,0x95,0x1d,0x4b,0xf1,0x65,
        0xe6,0xc6,0xb7,0x21,0xef,0xad,0xa9,0x85,0xfb,0x41,0x66,0x1b,0xc6,0xe7,0xfd,0x6c,
    };
    static const u8 three_g_y[32] = {
        0x87,0x34,0x64,0x0c,0x49,0x98,0xff,0x7e,0x37,0x4b,0x06,0xce,0x1a,0x64,0xa2,0xec,
        0xd8,0x2a,0xb0,0x36,0x38,0x4f,0xb8,0x3d,0x9a,0x79,0xb1,0x27,0xa2,0x7d,0x50,0x32,
    };
    bn_to_bytes_be(&three_g.x, out, 32);
    if (!bytes_eq(out, three_g_x, 32))
        return false;
    bn_to_bytes_be(&three_g.y, out, 32);
    if (!bytes_eq(out, three_g_y, 32))
        return false;

    /* P-256: on-curve validation must accept G itself and reject an
       obviously-off-curve point */
    if (!p256_point_on_curve(&p256_gx, &p256_gy))
        return false;
    bignum_t bogus_y;
    bn_addmod(&bogus_y, &p256_gy, &bn_one, &p256_p);
    if (p256_point_on_curve(&p256_gx, &bogus_y))
        return false;

    /* P-256 ECDHE: k1*(k2*G) == k2*(k1*G), the exact property TLS's
       ECDHE key exchange relies on -- fixed test scalars (not RDRAND),
       cross-checked against the same Python reference above, which
       also confirmed shared_secret_match == True for these values */
    static const u8 k1_b[31] = {
        0x12,0x34,0x56,0x78,0x90,0xab,0xcd,0xef,0x12,0x34,0x56,0x78,0x90,0xab,0xcd,0xef,
        0x12,0x34,0x56,0x78,0x90,0xab,0xcd,0xef,0x12,0x34,0x56,0x78,0x90,0xab,0xcd,
    };
    static const u8 k2_b[31] = {
        0xfe,0xdc,0xba,0x09,0x87,0x65,0x43,0x21,0xfe,0xdc,0xba,0x09,0x87,0x65,0x43,0x21,
        0xfe,0xdc,0xba,0x09,0x87,0x65,0x43,0x21,0xfe,0xdc,0xba,0x09,0x87,0x65,0x43,
    };
    static const u8 shared_x_expect[32] = {
        0x80,0xff,0x8c,0x50,0xd1,0x2c,0x9a,0xbf,0xd0,0xa3,0xbf,0xee,0x1e,0x8c,0x14,0xe7,
        0x58,0x07,0x82,0x59,0x82,0x1c,0xd8,0x24,0xc8,0xf9,0x09,0x98,0x74,0x54,0xa5,0x77,
    };
    u8 k1_full[32] = {0}, k2_full[32] = {0};
    memcpy(k1_full + 1, k1_b, 31); /* k1/k2 are 31 bytes wide; left-pad
                                       the top byte with 0 to fill priv[32] */
    memcpy(k2_full + 1, k2_b, 31);

    u8 p1x[32], p1y[32], p2x[32], p2y[32], s1x[32], s2x[32];
    bignum_t bk1, bk2;
    bn_from_bytes_be(&bk1, k1_full, 32);
    bn_from_bytes_be(&bk2, k2_full, 32);
    ec_point_t ep1, ep2;
    ec_scalar_mult(&ep1, &bk1, &g);
    ec_scalar_mult(&ep2, &bk2, &g);
    bn_to_bytes_be(&ep1.x, p1x, 32);
    bn_to_bytes_be(&ep1.y, p1y, 32);
    bn_to_bytes_be(&ep2.x, p2x, 32);
    bn_to_bytes_be(&ep2.y, p2y, 32);

    if (!p256_ecdh_shared_secret(k1_full, p2x, p2y, s1x))
        return false;
    if (!p256_ecdh_shared_secret(k2_full, p1x, p1y, s2x))
        return false;
    if (!bytes_eq(s1x, s2x, 32))
        return false;
    if (!bytes_eq(s1x, shared_x_expect, 32))
        return false;

    /* a peer point that's off-curve must be rejected outright, never
       silently combined into a "shared secret" */
    u8 bogus_peer_y[32];
    memcpy(bogus_peer_y, p2y, 32);
    bogus_peer_y[31] ^= 0x01;
    u8 reject_out[32];
    if (p256_ecdh_shared_secret(k1_full, p2x, bogus_peer_y, reject_out))
        return false;

    /* RDRAND-backed key generation: if the hardware/hypervisor exposes
       RDRAND, a generated keypair's public point must land on the
       curve and a full generate+generate+ECDH round trip must agree
       from both sides (mirrors the fixed-scalar check above but with
       genuinely random scalars). If RDRAND isn't available, this is
       skipped rather than failing the whole self-test -- crypto_ok
       still gates TLS, but a machine without RDRAND simply can't do
       ECDHE at all, which p256_generate_keypair's own false return
       already enforces at the point of use. */
    u8 rpriv1[32], rpub1x[32], rpub1y[32];
    u8 rpriv2[32], rpub2x[32], rpub2y[32];
    if (crypto_random_bytes(out, 4)) { /* RDRAND present -- exercise the full path */
        if (!p256_generate_keypair(rpriv1, rpub1x, rpub1y))
            return false;
        if (!p256_generate_keypair(rpriv2, rpub2x, rpub2y))
            return false;
        bignum_t rx1, ry1;
        bn_from_bytes_be(&rx1, rpub1x, 32);
        bn_from_bytes_be(&ry1, rpub1y, 32);
        if (!p256_point_on_curve(&rx1, &ry1))
            return false;
        u8 rs1[32], rs2[32];
        if (!p256_ecdh_shared_secret(rpriv1, rpub2x, rpub2y, rs1))
            return false;
        if (!p256_ecdh_shared_secret(rpriv2, rpub1x, rpub1y, rs2))
            return false;
        if (!bytes_eq(rs1, rs2, 32))
            return false;
    }

    /* RSA PKCS#1 v1.5 / SHA-256 signature verification, cross-checked
       against a real 2048-bit key generated and signed independently
       by PyCryptodome (Crypto.PublicKey.RSA + Crypto.Signature.pkcs1_15),
       not anything this codebase produced itself */
    static const u8 rsa_test_n[256] = {
        0xde,0xaf,0xc2,0x66,0xf8,0x7e,0x50,0x40,0xee,0x1c,0x6c,0xef,0x54,0x8f,0xa8,0xc5,
        0x2c,0xd7,0xaa,0x34,0xb2,0x12,0x34,0x13,0x48,0x4e,0xaa,0xd7,0x43,0x3e,0x57,0x9e,
        0x55,0xd0,0xf7,0xf2,0xe3,0x8d,0x8c,0xb5,0xa7,0xc4,0xe5,0xbf,0x26,0x4b,0xc7,0xac,
        0xf0,0xb0,0x30,0x98,0x31,0xc2,0x40,0x79,0xb3,0x32,0xe3,0xbe,0x7a,0x4a,0xc5,0xed,
        0x92,0x28,0x6f,0x85,0xe6,0xb7,0x8e,0x55,0x56,0x90,0xd2,0x68,0x12,0x2e,0x1a,0x30,
        0x0c,0x9e,0xe1,0xcb,0xa5,0x6a,0x7c,0x03,0x52,0xbe,0x1b,0x9e,0x50,0xc9,0x87,0x80,
        0x4f,0x1b,0x2a,0x99,0x71,0x97,0xc7,0x13,0xf0,0x12,0xb9,0x1c,0x3e,0x83,0xb4,0x75,
        0x59,0x90,0xeb,0x28,0x48,0x96,0x3c,0x0a,0x95,0xcc,0x90,0x91,0x38,0xec,0x7b,0xb7,
        0x15,0xe5,0x99,0xb8,0xde,0x9d,0x47,0x2e,0xaf,0x5a,0x4c,0x0f,0x22,0xf0,0x75,0x72,
        0xfc,0x11,0x41,0x01,0x74,0x14,0x6c,0x65,0xb0,0x20,0x90,0x8b,0x9b,0x36,0x4b,0x59,
        0x11,0xa0,0xd4,0x92,0xdf,0x4a,0x1f,0x0e,0x4b,0xcd,0x67,0x14,0x27,0xef,0x3c,0x04,
        0xb2,0x7e,0x12,0xb2,0x2b,0x28,0xf4,0x88,0xde,0xe8,0x86,0x30,0x9c,0xe1,0x17,0x20,
        0x6a,0x84,0x11,0x52,0xea,0xeb,0x75,0x2b,0xd2,0xa8,0x23,0xd4,0xeb,0x06,0x7c,0x00,
        0x50,0x2a,0x15,0x7a,0x35,0x2b,0xa7,0x6d,0x74,0x4e,0xcf,0x53,0x47,0xc2,0xbc,0x70,
        0xd6,0x7d,0xa0,0xdd,0x7f,0x45,0x46,0x8e,0x82,0xcf,0x17,0xfa,0xb6,0x95,0xad,0x86,
        0x8c,0xbe,0xe4,0x9d,0x6a,0x62,0x76,0x1e,0x5d,0xe4,0x62,0x9d,0x59,0xc5,0x11,0xad,
    };
    static const u8 rsa_test_sig[256] = {
        0xd9,0xd8,0x60,0x51,0x2b,0x3c,0xab,0xa1,0x11,0x4c,0x78,0xb3,0x9a,0xe2,0xb6,0x0d,
        0x7a,0x27,0x6e,0x5c,0x7e,0x23,0xa1,0x44,0x79,0xe1,0x54,0x6b,0x53,0x1e,0x3a,0x68,
        0x1c,0x3a,0x77,0xdc,0x3c,0x6c,0x1e,0x90,0xb7,0xc1,0xee,0x05,0xea,0xdf,0xf3,0xa4,
        0x2f,0xd2,0x6c,0x7d,0xde,0x1a,0x8d,0x14,0xc1,0x17,0xbc,0x6b,0x18,0x4b,0xaf,0x94,
        0xdc,0x36,0x6a,0xde,0xdf,0xd5,0xcf,0x08,0x72,0x5b,0xe3,0xe0,0xab,0x83,0xe2,0xa6,
        0xad,0x9f,0xd6,0x25,0x46,0x02,0x43,0xc9,0x74,0x89,0xca,0x55,0x8a,0x58,0xb2,0x00,
        0x2e,0x7f,0xd8,0x47,0xed,0x29,0xc8,0xe5,0xb4,0xe0,0x56,0x6c,0x3f,0xa7,0x06,0x4b,
        0x56,0x12,0x73,0x9c,0xb4,0x6e,0x44,0x3c,0x8d,0xb6,0x06,0x3a,0x02,0x2a,0xf8,0xee,
        0xf4,0x14,0x58,0x55,0xf5,0x95,0x0a,0xff,0xd0,0xe8,0x69,0xb6,0x51,0x77,0x59,0x28,
        0xf6,0x4a,0x14,0xb5,0xd1,0xa5,0xc8,0xf9,0xd3,0x1f,0x62,0x9c,0x7d,0xc7,0x3d,0xd3,
        0x2a,0xf1,0xa2,0x70,0xe8,0x1d,0x5e,0x82,0xd7,0xff,0x8e,0x3c,0xaa,0x4d,0x50,0xec,
        0x30,0x2b,0x56,0xcd,0x2a,0x7a,0xbd,0xfc,0x30,0xed,0x86,0x65,0xe0,0x9f,0x5f,0x62,
        0x0c,0x62,0xa8,0xad,0xfc,0x9d,0xa2,0x91,0x0d,0x21,0x8e,0x19,0x3b,0xaf,0xff,0xd2,
        0x67,0x76,0x0c,0x04,0x62,0x15,0x21,0xdc,0x78,0x9a,0x38,0x7c,0x49,0xe9,0x64,0xd6,
        0x83,0x04,0x01,0x3c,0xfe,0x69,0x40,0xe0,0xb3,0xdb,0x70,0xd3,0x09,0xcd,0xde,0x18,
        0x7d,0xc8,0x02,0xde,0xaa,0x5c,0x4c,0xae,0xad,0xfd,0xbf,0x21,0x37,0x14,0x09,0x8d,
    };
    static const u8 rsa_test_hash[32] = {
        0x8d,0x1e,0x9f,0xaa,0xa4,0x37,0x07,0x0a,0x36,0xc7,0x20,0x4b,0xbc,0xdc,0x1d,0x37,
        0x52,0x65,0xfb,0x73,0x4a,0x83,0xc8,0x13,0x88,0x15,0xed,0x12,0x0d,0x03,0x51,0x86,
    };
    bignum_t rsa_n, rsa_e, rsa_sig;
    bn_from_bytes_be(&rsa_n, rsa_test_n, 256);
    bn_from_bytes_be(&rsa_sig, rsa_test_sig, 256);
    bn_zero(&rsa_e);
    rsa_e.limb[0] = 65537;

    if (!rsa_verify_pkcs1v15_sha256(&rsa_n, &rsa_e, &rsa_sig, 256, rsa_test_hash))
        return false; /* a valid signature must verify */

    u8 bad_hash[32];
    memcpy(bad_hash, rsa_test_hash, 32);
    bad_hash[0] ^= 0x01;
    if (rsa_verify_pkcs1v15_sha256(&rsa_n, &rsa_e, &rsa_sig, 256, bad_hash))
        return false; /* wrong hash must NOT verify */

    bignum_t bad_sig;
    bad_sig = rsa_sig;
    bad_sig.limb[0] ^= 0x1;
    if (rsa_verify_pkcs1v15_sha256(&rsa_n, &rsa_e, &bad_sig, 256, rsa_test_hash))
        return false; /* corrupted signature must NOT verify */

    bignum_t wrong_e;
    bn_zero(&wrong_e);
    wrong_e.limb[0] = 3; /* a different (but still plausible) public
                            exponent must NOT verify this signature */
    if (rsa_verify_pkcs1v15_sha256(&rsa_n, &wrong_e, &rsa_sig, 256, rsa_test_hash))
        return false;

    return true;
}
