#!/usr/bin/env python3
"""
mkimports.py — generate the IAT + call trampolines for Windows-style
AlphaOS apps from an import manifest.

Emits an assembly file with:
  .iat  — one 4-byte slot per import (per DLL, zero-terminated), the
          exact layout tools/mkpe.py describes in the PE import
          directory; the loader patches these slots at exec time.
  .text — `Func: jmp *__imp_Func` trampolines so C code can call the
          imports as ordinary functions (stdcall passes through jmp).

usage: mkimports.py <imports.list> <out.S>
"""
import sys


def parse_manifest(path):
    dlls = []
    with open(path) as fp:
        for line in fp:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            dlls.append((parts[0], parts[1:]))
    return dlls


def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <imports.list> <out.S>")
    dlls = parse_manifest(sys.argv[1])

    out = ["/* generated by tools/mkimports.py — do not edit */",
           '.section .iat, "aw", @progbits']
    for dll, funcs in dlls:
        out.append(f"/* {dll} */")
        for fn in funcs:
            out.append(f"__imp_{fn}: .long 0")
        out.append(".long 0")
    out.append("")
    out.append(".section .text")
    for _, funcs in dlls:
        for fn in funcs:
            out.append(f".global {fn}")
            out.append(f"{fn}: jmp *__imp_{fn}")
    out.append("")
    out.append('.section .note.GNU-stack, "", @progbits')

    with open(sys.argv[2], "w") as fp:
        fp.write("\n".join(out) + "\n")
    n = sum(len(f) for _, f in dlls)
    print(f"{sys.argv[2]}: {n} imports from {len(dlls)} dll(s)")


if __name__ == "__main__":
    main()
