#!/usr/bin/env python3
"""
mkpe.py — wrap a flat code+data blob into a valid PE32+ (x86-64 .exe)
image.

Apps are compiled with GCC for x86-64, linked at ImageBase+0x1000 (see
apps/app.ld), flattened with objcopy, and packaged here with a proper
DOS header, COFF header, PE32+ optional header, and a single RWX
section. The result is a structurally valid PE file: the AlphaOS
loader (and any PE tool, e.g. `file`, `objdump -p`, or `pefile`) parses
it as a genuine 64-bit Windows executable.

With --imports <manifest>, a real PE import directory is emitted: the
.iat slots generated by mkimports.py (IMAGE_THUNK_DATA64, 8 bytes each)
sit at the very start of the blob (RVA 0x1000), and the descriptors /
lookup tables / hint-name strings are appended after the image's bss.
The AlphaOS loader (or any PE loader) resolves them the standard way.

usage: mkpe.py <flat.bin> <out.exe> [--bss N] [--base 0x40000000]
                                    [--entry RVA] [--imports LIST]
"""
import argparse
import struct
import time

SECTION_ALIGN = 0x1000
FILE_ALIGN = 0x200


def align(v, a):
    return (v + a - 1) & ~(a - 1)


def parse_manifest(path):
    dlls = []
    with open(path) as fp:
        for line in fp:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            dlls.append((parts[0], parts[1:]))
    return dlls


def build_import_meta(dlls, iat_rva, meta_rva):
    """Build import descriptors + lookup tables + hint/name strings.
    IAT slot layout must match mkimports.py: per DLL, one 8-byte
    IMAGE_THUNK_DATA64 slot per function, followed by a zero
    terminator. IMAGE_IMPORT_DESCRIPTOR itself is unchanged from PE32
    (its RVA fields are always 32-bit)."""
    ndesc = len(dlls) + 1
    ilt_off = ndesc * 20
    ilts_size = sum(8 * (len(funcs) + 1) for _, funcs in dlls)
    str_off = ilt_off + ilts_size

    strings = b""
    hint_rva = {}
    for dll, funcs in dlls:
        for fn in funcs:
            if len(strings) % 2:
                strings += b"\0"
            hint_rva[(dll, fn)] = meta_rva + str_off + len(strings)
            strings += struct.pack("<H", 0) + fn.encode() + b"\0"
    name_rva = {}
    for dll, _ in dlls:
        name_rva[dll] = meta_rva + str_off + len(strings)
        strings += dll.encode() + b"\0"

    descs = b""
    ilts = b""
    iat_cursor = iat_rva
    ilt_cursor = meta_rva + ilt_off
    for dll, funcs in dlls:
        descs += struct.pack("<IIIII", ilt_cursor, 0, 0, name_rva[dll],
                             iat_cursor)
        for fn in funcs:
            ilts += struct.pack("<Q", hint_rva[(dll, fn)])
        ilts += struct.pack("<Q", 0)
        ilt_cursor += 8 * (len(funcs) + 1)
        iat_cursor += 8 * (len(funcs) + 1)
    descs += b"\0" * 20  # terminator

    iat_size = iat_cursor - iat_rva
    return descs + ilts + strings, iat_size


def build(blob: bytes, bss: int, image_base: int, entry_rva: int,
          imports) -> bytes:
    text_rva = SECTION_ALIGN

    import_dir = (0, 0)
    iat_dir = (0, 0)
    if imports:
        # metadata goes after code+data+bss; store bss as file zeros so
        # nothing overlaps it
        meta_rva = text_rva + align(len(blob) + bss, 8)
        meta, iat_size = build_import_meta(imports, text_rva, meta_rva)
        iat_slots = sum(len(f) + 1 for _, f in imports) * 8
        assert iat_size == iat_slots
        assert len(blob) >= iat_size, ".iat section missing from blob"
        import_dir = (meta_rva, (len(imports) + 1) * 20)
        iat_dir = (text_rva, iat_size)
        blob = blob + b"\0" * (meta_rva - text_rva - len(blob)) + meta
        bss = 0  # already materialized as file zeros above

    vsize = len(blob) + bss
    raw_size = align(len(blob), FILE_ALIGN)
    size_of_image = align(text_rva + vsize, SECTION_ALIGN)
    size_of_headers = FILE_ALIGN

    # --- DOS header: 'MZ', e_lfanew -> PE header directly at 0x40
    dos = struct.pack("<2s", b"MZ") + b"\0" * 58 + struct.pack("<I", 0x40)
    assert len(dos) == 0x40

    # --- COFF file header
    IMAGE_FILE_MACHINE_AMD64 = 0x8664
    # RELOCS_STRIPPED (no .reloc section emitted) | EXECUTABLE_IMAGE |
    # LARGE_ADDRESS_AWARE (customary for x64 images)
    characteristics = 0x0023
    coff = struct.pack(
        "<HHIIIHH",
        IMAGE_FILE_MACHINE_AMD64,
        1,                    # NumberOfSections
        int(time.time()),
        0, 0,                 # no symbol table
        0xF0,                 # SizeOfOptionalHeader (PE32+, 16 data dirs)
        characteristics,
    )

    # --- PE32+ optional header (IMAGE_OPTIONAL_HEADER64): 0x70 fixed
    # fields (no BaseOfData; ImageBase/stack/heap fields are 8 bytes)
    # + 16 x 8-byte data directories = 0xF0 total.
    opt = struct.pack(
        "<HBBIIIIIQIIHHHHHHIIIIHHQQQQII",
        0x20B,                # PE32+
        1, 0,                 # linker version
        raw_size,             # SizeOfCode
        0, bss,               # init/uninit data sizes
        entry_rva,            # AddressOfEntryPoint
        text_rva,             # BaseOfCode
        image_base,           # ImageBase (8 bytes)
        SECTION_ALIGN, FILE_ALIGN,
        1, 0,                 # OS version
        0, 0,                 # image version
        3, 10,                # subsystem version
        0,                    # Win32VersionValue
        size_of_image,
        size_of_headers,
        0,                    # checksum
        3,                    # Subsystem: CUI
        0,                    # DllCharacteristics
        0x100000, 0x1000,     # stack reserve/commit (8 bytes each)
        0x100000, 0x1000,     # heap reserve/commit (8 bytes each)
        0,                    # LoaderFlags
        16,                   # NumberOfRvaAndSizes
    )
    # data directories: 1 = imports, 12 = IAT
    dirs = [(0, 0)] * 16
    dirs[1] = import_dir
    dirs[12] = iat_dir
    opt += b"".join(struct.pack("<II", rva, size) for rva, size in dirs)
    assert len(opt) == 0xF0

    # --- section table: one RWX ".text" holding code+data, bss as tail
    IMAGE_SCN = 0xE0000060    # CODE|INIT_DATA|EXECUTE|READ|WRITE
    section = struct.pack(
        "<8sIIIIIIHHI",
        b".text\0\0\0",
        vsize,                # VirtualSize (includes .bss)
        text_rva,             # VirtualAddress
        raw_size,             # SizeOfRawData
        size_of_headers,      # PointerToRawData
        0, 0, 0, 0,
        IMAGE_SCN,
    )

    headers = dos + b"PE\0\0" + coff + opt + section
    assert len(headers) <= size_of_headers, "headers overflow one sector"
    headers += b"\0" * (size_of_headers - len(headers))

    return headers + blob + b"\0" * (raw_size - len(blob))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("blob")
    ap.add_argument("out")
    ap.add_argument("--bss", type=lambda v: int(v, 0), default=0)
    ap.add_argument("--base", type=lambda v: int(v, 0), default=0x40000000)
    ap.add_argument("--entry", type=lambda v: int(v, 0), default=0x1000)
    ap.add_argument("--imports", help="import manifest (see mkimports.py)")
    args = ap.parse_args()

    with open(args.blob, "rb") as fp:
        blob = fp.read()
    imports = parse_manifest(args.imports) if args.imports else None
    exe = build(blob, args.bss, args.base, args.entry, imports)
    with open(args.out, "wb") as fp:
        fp.write(exe)
    nimp = sum(len(f) for _, f in imports) if imports else 0
    print(f"{args.out}: {len(exe)} bytes "
          f"(code+data {len(blob)}, bss {args.bss}, imports {nimp}, "
          f"base {args.base:#x})")


if __name__ == "__main__":
    main()
